# Generated by Django 5.1.15 on 2026-09-22 19:49

import common.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_type', models.CharField(choices=[('TRUSTEE_GROUP', 'Trustee Communication'), ('ADVISOR_GROUP', 'Advisor Communication'), ('VOLUNTEER_GROUP', 'Volunteer Communication')], db_index=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role Conversation Channel',
                'verbose_name_plural': 'Role Conversation Channels',
                'ordering': ['group_type'],
            },
        ),
        migrations.CreateModel(
            name='RoleMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_role', models.CharField(help_text='Snapshot of sender role at time of posting: ADMIN, TRUSTEE, ADVISOR, or VOLUNTEER', max_length=30)),
                ('content', models.TextField(blank=True, max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.roleconversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Message',
                'verbose_name_plural': 'Role Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleConversationReadState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='communications.roleconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_chat_read_states', to=settings.AUTH_USER_MODEL)),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='communications.rolemessage')),
            ],
            options={
                'verbose_name': 'Role Conversation Read State',
                'verbose_name_plural': 'Role Conversation Read States',
            },
        ),
        migrations.CreateModel(
            name='RoleMessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(storage=common.storage.PrivateMediaStorage(), upload_to='communications/attachments/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communications.rolemessage')),
            ],
            options={
                'verbose_name': 'Role Message Attachment',
                'verbose_name_plural': 'Role Message Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rolemessage',
            index=models.Index(fields=['conversation', 'created_at'], name='communicati_convers_22f89b_idx'),
        ),
        migrations.AddIndex(
            model_name='rolemessage',
            index=models.Index(fields=['sender', 'created_at'], name='communicati_sender__40e852_idx'),
        ),
        migrations.AddIndex(
            model_name='roleconversationreadstate',
            index=models.Index(fields=['user', 'conversation'], name='communicati_user_id_73c99e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roleconversationreadstate',
            unique_together={('conversation', 'user')},
        ),
    ]
