# Generated by Django 5.1.4 on 2026-08-20 19:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohorts', '0004_cohort_lst_batch_alter_cohort_status'),
        ('courses', '0009_course_course_prerequisites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_type', models.CharField(choices=[('PRESCREENING', 'Pre-Screening'), ('MODULE_TEST', 'Module Test')], db_index=True, help_text='PRESCREENING = prerequisite questions, MODULE_TEST = syllabus questions.', max_length=20)),
                ('title', models.CharField(help_text='E.g. "VLSI Prerequisites Paper" or "Module 3 — Digital Design Test".', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('MIXED', 'Mixed')], default='EASY', max_length=20)),
                ('source_topics', models.JSONField(blank=True, default=list, help_text='List of topics the questions are based on. Auto-populated from Course.course_prerequisites (pre-screening) or CourseModule.topics (module test).')),
                ('sets_data', models.JSONField(blank=True, default=dict, help_text='Paper sets stored as {"A": {"label": "Paper A", "questions": [...]}, "B": {...}, "C": {...}, "D": {...}}.')),
                ('total_questions_per_set', models.PositiveIntegerField(default=10, help_text='Number of questions in each paper set.')),
                ('is_ai_generated', models.BooleanField(default=False, help_text='Whether the questions were generated by AI.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('cohort', models.ForeignKey(blank=True, help_text='Required for MODULE_TEST banks. The cohort this bank is assigned to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_banks', to='cohorts.cohort')),
                ('course', models.ForeignKey(help_text='The course this question bank belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_question_banks', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, help_text='Required for MODULE_TEST banks. The module whose syllabus topics are tested.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_banks', to='courses.coursemodule')),
            ],
            options={
                'verbose_name': 'Question Bank',
                'verbose_name_plural': 'Question Banks',
                'ordering': ('-created_at',),
            },
        ),
    ]
