# Generated by Django 5.1.4 on 2026-08-20 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_moduletest_cohort_moduletestsubmission_cohort'),
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='exam',
            field=models.ForeignKey(blank=True, help_text='Optional Pre-Screening Exam linked to this question bank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_banks', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='module_test',
            field=models.ForeignKey(blank=True, help_text='Optional Module Test linked to this question bank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_banks', to='exams.moduletest'),
        ),
    ]
