# Generated by Django 5.1.4 on 2026-08-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0002_questionbank_exam_questionbank_module_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='status',
            field=models.CharField(choices=[('GENERATING', 'Generating'), ('APPROVED', 'Approved'), ('FAILED', 'Failed')], db_index=True, default='APPROVED', max_length=20),
        ),
    ]
