# Generated by Django 5.1.4 on 2026-08-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0003_questionbank_error_message_questionbank_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='status',
            field=models.CharField(choices=[('GENERATING', 'Generating'), ('PROCESSING', 'Processing'), ('APPROVED', 'Approved'), ('FAILED', 'Failed')], db_index=True, default='APPROVED', max_length=20),
        ),
    ]
