# Generated by Django 5.1.4 on 2026-08-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0004_alter_questionbank_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='lifecycle_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', help_text='Global exam access state for students.', max_length=20),
        ),
    ]
