from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models

from common.models import TimeStampedUUIDModel


class QuestionBank(TimeStampedUUIDModel):
    """
    Stores question paper sets (A, B, C, D) in structured JSON format.

    Two bank types:
      - PRESCREENING: Easy prerequisite-level questions sourced from Course.course_prerequisites
      - MODULE_TEST:  Syllabus-level questions sourced from CourseModule.topics
    """

    class BankType(models.TextChoices):
        PRESCREENING = "PRESCREENING", "Pre-Screening"
        MODULE_TEST = "MODULE_TEST", "Module Test"

    class Difficulty(models.TextChoices):
        EASY = "EASY", "Easy"
        MEDIUM = "MEDIUM", "Medium"
        HARD = "HARD", "Hard"
        MIXED = "MIXED", "Mixed"

    class Status(models.TextChoices):
        GENERATING = "GENERATING", "Generating"
        PROCESSING = "PROCESSING", "Processing"
        APPROVED = "APPROVED", "Approved"
        FAILED = "FAILED", "Failed"

    class LifecycleStatus(models.TextChoices):
        DRAFT = "DRAFT", "Draft"
        OPEN = "OPEN", "Open"
        CLOSED = "CLOSED", "Closed"


    bank_type = models.CharField(
        max_length=20,
        choices=BankType.choices,
        db_index=True,
        help_text="PRESCREENING = prerequisite questions, MODULE_TEST = syllabus questions.",
    )
    course = models.ForeignKey(
        "courses.Course",
        on_delete=models.CASCADE,
        related_name="question_banks",
        help_text="The course this question bank belongs to.",
    )
    cohort = models.ForeignKey(
        "cohorts.Cohort",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="question_banks",
        help_text="Required for MODULE_TEST banks. The cohort this bank is assigned to.",
    )
    module = models.ForeignKey(
        "courses.CourseModule",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="question_banks",
        help_text="Required for MODULE_TEST banks. The module whose syllabus topics are tested.",
    )
    exam = models.ForeignKey(
        "exams.Exam",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="question_banks",
        help_text="Optional Pre-Screening Exam linked to this question bank.",
    )
    module_test = models.ForeignKey(
        "exams.ModuleTest",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="question_banks",
        help_text="Optional Module Test linked to this question bank.",
    )
    title = models.CharField(
        max_length=255,
        help_text='E.g. "VLSI Prerequisites Paper" or "Module 3 — Digital Design Test".',
    )
    description = models.TextField(blank=True, null=True)
    difficulty = models.CharField(
        max_length=20,
        choices=Difficulty.choices,
        default=Difficulty.EASY,
    )
    source_topics = models.JSONField(
        default=list,
        blank=True,
        help_text=(
            "List of topics the questions are based on. "
            "Auto-populated from Course.course_prerequisites (pre-screening) "
            "or CourseModule.topics (module test)."
        ),
    )
    sets_data = models.JSONField(
        default=dict,
        blank=True,
        help_text=(
            'Paper sets stored as {"A": {"label": "Paper A", "questions": [...]}, '
            '"B": {...}, "C": {...}, "D": {...}}.'
        ),
    )
    total_questions_per_set = models.PositiveIntegerField(
        default=10,
        help_text="Number of questions in each paper set.",
    )
    is_ai_generated = models.BooleanField(
        default=False,
        help_text="Whether the questions were generated by AI.",
    )
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.APPROVED,
        db_index=True,
    )
    lifecycle_status = models.CharField(
        max_length=20,
        choices=LifecycleStatus.choices,
        default=LifecycleStatus.DRAFT,
        db_index=True,
        help_text="Global exam access state for students."
    )
    error_message = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(default=True, db_index=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="created_question_banks",
    )

    class Meta:
        verbose_name = "Question Bank"
        verbose_name_plural = "Question Banks"
        ordering = ("-created_at",)

    def __str__(self):
        return f"[{self.get_bank_type_display()}] {self.title} ({self.course.code})"

    def clean(self):
        super().clean()
        if self.cohort_id and self.course_id and self.cohort.course_id != self.course_id:
            raise ValidationError({"cohort": "The cohort must belong to the selected course."})
        if self.module_id and self.course_id and self.module.course_id != self.course_id:
            raise ValidationError({"module": "The module must belong to the selected course."})
        if self.exam_id:
            if self.bank_type != self.BankType.PRESCREENING:
                raise ValidationError({"exam": "Only pre-screening banks can link a pre-screening exam."})
            if self.course_id and self.exam.application.course_id != self.course_id:
                raise ValidationError({"exam": "The exam must belong to the selected course."})
        if self.module_test_id:
            if self.bank_type != self.BankType.MODULE_TEST:
                raise ValidationError({"module_test": "Only module-test banks can link a module test."})
            if self.course_id and self.module_test.course_id != self.course_id:
                raise ValidationError({"module_test": "The module test must belong to the selected course."})
            if self.module_id and self.module_test.module_id and self.module_test.module_id != self.module_id:
                raise ValidationError({"module_test": "The module test belongs to a different module."})
            if self.cohort_id and self.module_test.cohort_id and self.module_test.cohort_id != self.cohort_id:
                raise ValidationError({"module_test": "The module test belongs to a different cohort."})
        if self.bank_type == self.BankType.MODULE_TEST:
            if not self.cohort_id:
                raise ValidationError(
                    {"cohort": "Cohort is required for Module Test question banks."}
                )
            if not self.module_id:
                raise ValidationError(
                    {"module": "Module is required for Module Test question banks."}
                )
        elif self.module_test_id:
            raise ValidationError({"module_test": "A pre-screening bank cannot link a module test."})

    def save(self, *args, **kwargs):
        # Auto-populate source_topics if empty
        if not self.source_topics:
            if self.bank_type == self.BankType.PRESCREENING and self.course_id:
                try:
                    course = self.course
                    if course.course_prerequisites:
                        self.source_topics = course.course_prerequisites
                except Exception:
                    pass
            elif self.bank_type == self.BankType.MODULE_TEST and self.module_id:
                try:
                    module = self.module
                    if module.topics:
                        self.source_topics = module.topics
                except Exception:
                    pass

        # Default difficulty for pre-screening banks
        if self.bank_type == self.BankType.PRESCREENING and not self.difficulty:
            self.difficulty = self.Difficulty.EASY

        super().save(*args, **kwargs)

    @property
    def set_codes(self):
        """Return list of available set codes (e.g. ['A', 'B', 'C', 'D'])."""
        if isinstance(self.sets_data, dict):
            return sorted(self.sets_data.keys())
        return []

    @property
    def total_sets(self):
        """Return count of paper sets."""
        if isinstance(self.sets_data, dict):
            return len(self.sets_data)
        return 0

    def get_paper_set(self, set_code):
        """Return a specific paper set by code (e.g. 'A', 'B', 'C', 'D')."""
        if isinstance(self.sets_data, dict):
            return self.sets_data.get(set_code.upper())
        return None
