# Generated by Django 5.1.4 on 2026-08-04 07:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('PRESCREENING_PENDING', 'Pre-Screening Pending'), ('PRESCREENING_COMPLETED', 'Pre-Screening Completed'), ('EXAM_PENDING', 'Exam Pending'), ('EXAM_COMPLETED', 'Exam Completed'), ('QUALIFIED', 'Qualified'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted'), ('COHORT_ASSIGNED', 'Cohort Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped')], default='APPLIED', max_length=30),
        ),
        migrations.CreateModel(
            name='PreScreening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewer', models.CharField(blank=True, max_length=150, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='SCHEDULED', max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pre_screening', to='applications.application')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
