# Generated by Django 5.1.4 on 2026-08-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_prescreeninginterview'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='offer_letter_file',
            field=models.FileField(blank=True, null=True, upload_to='offer_letters/'),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_letter_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_letter_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_letter_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('PRESCREENING_PENDING', 'Pre-Screening Pending'), ('PRESCREENING_COMPLETED', 'Pre-Screening Completed'), ('EXAM_PENDING', 'Exam Pending'), ('EXAM_COMPLETED', 'Exam Completed'), ('QUALIFIED', 'Qualified'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted'), ('COHORT_ASSIGNED', 'Cohort Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped')], db_index=True, default='APPLIED', max_length=30),
        ),
        migrations.AlterField(
            model_name='prescreening',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], db_index=True, default='SCHEDULED', max_length=30),
        ),
        migrations.AlterField(
            model_name='prescreeninginterview',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], db_index=True, default='SCHEDULED', max_length=30),
        ),
    ]
