# Generated by Django 5.1.4 on 2026-08-15 06:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_status_cancelled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('TREE_PLANTATION', 'Tree Plantation'), ('BLOOD_DONATION', 'Blood Donation'), ('HELPING_SOCIETY', 'Helping Society')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('activity_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('evidence_url', models.URLField(blank=True, max_length=500, null=True)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='journey/community/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_remarks', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_activities', to='applications.application')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_community_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
                'indexes': [models.Index(fields=['application', 'activity_type', 'status'], name='application_applica_a04128_idx')],
            },
        ),
    ]
