# Generated by Django 5.1.4 on 2026-08-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_communityactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescreening',
            options={'verbose_name': 'Screening Exam Schedule', 'verbose_name_plural': 'Screening Exam Schedules'},
        ),
        migrations.AlterModelOptions(
            name='prescreeninginterview',
            options={'verbose_name': 'Candidate Interview', 'verbose_name_plural': 'Candidate Interviews'},
        ),
        migrations.AlterField(
            model_name='prescreeninginterview',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RESCHEDULED', 'Rescheduled'), ('COMPLETED', 'Completed'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], db_index=True, default='SCHEDULED', max_length=30),
        ),
    ]
