# Generated by Django 5.1.4 on 2026-08-15 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def repair_workflow_data(apps, schema_editor):
    Application = apps.get_model("applications", "Application")
    PreScreeningInterview = apps.get_model("applications", "PreScreeningInterview")
    database = schema_editor.connection.alias

    orphaned = Application.objects.using(database).filter(
        status__in=["COHORT_ASSIGNED", "IN_PROGRESS"],
        assigned_cohort__isnull=True,
    )
    orphaned.filter(qualified=True).update(status="QUALIFIED")
    orphaned.filter(qualified=False).update(status="REJECTED")
    orphaned.filter(qualified__isnull=True).update(status="EXAM_COMPLETED")

    assigned = Application.objects.using(database).filter(
        assigned_cohort__isnull=False,
        qualified=True,
    ).select_related("course", "student", "student__user")
    for application in assigned.iterator():
        student = application.student
        profiles_ready = bool(
            student.is_linkedin_connected
            and (student.is_github_connected or student.github_url)
            and not application.student.user.email.lower().endswith("@suretrust.local")
        )
        interview_ready = bool(
            not application.course.requires_interview
            or PreScreeningInterview.objects.using(database).filter(
                application_id=application.pk,
                status="PASSED",
            ).exists()
        )
        if profiles_ready and interview_ready:
            Application.objects.using(database).filter(pk=application.pk).update(
                role_verification_status="VERIFIED",
                role_verified_at=application.updated_at,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_prescreening_examiner_and_status'),
        ('cohorts', '0002_cohort_volunteers_alter_cohort_status'),
        ('courses', '0007_repair_coursemodule_schema'),
        ('students', '0004_studentprofile_student_identity_issued_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='role_verification_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='role_verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending admin verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='role_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='role_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_student_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='assigned_cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='cohorts.cohort'),
        ),
        migrations.RunPython(repair_workflow_data, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['COHORT_ASSIGNED', 'IN_PROGRESS']), _negated=True), ('assigned_cohort__isnull', False), _connector='OR'), name='cohort_status_requires_assigned_cohort'),
        ),
    ]
