# Generated by Django 5.1.4 on 2026-08-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('PRESCREENING_PENDING', 'Pre-Screening Pending'), ('PRESCREENING_COMPLETED', 'Pre-Screening Completed'), ('EXAM_PENDING', 'Exam Pending'), ('EXAM_COMPLETED', 'Exam Completed'), ('QUALIFIED', 'Qualified'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted'), ('COHORT_ASSIGNED', 'Cohort Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped'), ('SUSPENDED', 'Suspended'), ('TRANSFER_COHORT', 'Transfer Cohort'), ('CANCELLED', 'Cancelled')], db_index=True, default='APPLIED', max_length=30),
        ),
    ]
