# Generated by Django 5.1.4 on 2026-08-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='training_batch',
            field=models.CharField(blank=True, choices=[('BATCH_1', 'Batch 1'), ('BATCH_2', 'Batch 2'), ('BATCH_3', 'Batch 3'), ('BATCH_4', 'Batch 4')], default='BATCH_1', help_text='Assigned training batch for LST and Soft Skills training sessions.', max_length=20, null=True),
        ),
    ]
