# Generated by Django 5.1.4 on 2026-08-17 16:41

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_alter_application_application_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='offer_letter_file',
            field=models.FileField(blank=True, null=True, upload_to=applications.models.offer_letter_path),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('EXAM_PENDING', 'Exam Pending'), ('EXAM_COMPLETED', 'Exam Completed'), ('PRESCREENING_PENDING', 'Pre-Screen Interview Pending'), ('PRESCREENING_COMPLETED', 'Pre-Screen Interview Completed'), ('QUALIFIED', 'Qualified'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted'), ('COHORT_ASSIGNED', 'Cohort Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped'), ('SUSPENDED', 'Suspended'), ('TRANSFER_COHORT', 'Transfer Cohort'), ('CANCELLED', 'Cancelled')], db_index=True, default='APPLIED', max_length=30),
        ),
    ]
