# Generated by Django 5.1.4 on 2026-08-18 18:25

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_sync_application_exam_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityactivity',
            name='activity_type',
            field=models.CharField(choices=[('TREE_PLANTATION', 'Tree Plantation'), ('BLOOD_DONATION', 'Blood Donation'), ('HELPING_SOCIETY', 'Helping Society'), ('BLOG', 'Tech Blog Post'), ('OPEN_SOURCE', 'Open Source Contribution'), ('MEETUP', 'Tech Meetup / Webinar'), ('VOLUNTEER', 'Community Volunteering'), ('OTHER', 'Other Activity')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='communityactivity',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to=applications.models.community_evidence_path),
        ),
    ]
