# Generated by Django 5.1.4 on 2026-08-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_alter_communityactivity_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescreening',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Exam schedule window end time.', null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='prescreeninginterview',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Interview schedule window end time.', null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='prescreening',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='prescreeninginterview',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
    ]
