# Generated by Django 5.1.4 on 2026-08-22 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_application_offer_letter_revoke_reason_and_more'),
        ('cohorts', '0006_cohort_group_chat'),
        ('courses', '0010_course_requires_assignments_course_requires_capstone_and_more'),
        ('students', '0008_alter_studentprofile_profile_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatusAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True, default='')),
                ('is_repair', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Application Status Audit',
                'verbose_name_plural': 'Application Status Audits',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='application',
            name='offer_letter_status',
            field=models.CharField(choices=[('NOT_GENERATED', 'Not Generated'), ('GENERATING', 'Generating'), ('ISSUED', 'Issued'), ('REVOKED', 'Revoked'), ('FAILED', 'Failed')], db_index=True, default='NOT_GENERATED', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('offer_letter_hash__isnull', False), models.Q(('offer_letter_hash', ''), _negated=True)), fields=('offer_letter_hash',), name='unique_active_offer_letter_hash'),
        ),
        migrations.AddField(
            model_name='applicationstatusaudit',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationstatusaudit',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_audits', to='applications.application'),
        ),
    ]
