# Generated by Django 5.1.4 on 2026-08-22 19:37

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_applicationstatusaudit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='offer_letter_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=applications.models.offer_letter_path),
        ),
    ]
