# Generated by Django 5.1.4 on 2026-08-22 20:54

import applications.models
import common.storage
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def repair_historical_completion_invariants(apps, schema_editor):
    """Normalize legacy rows before PostgreSQL validates the new constraints."""
    Application = apps.get_model("applications", "Application")
    ApplicationStatusAudit = apps.get_model("applications", "ApplicationStatusAudit")
    Certificate = apps.get_model("certificates", "Certificate")
    database = schema_editor.connection.alias

    bad_completed = Application.objects.using(database).filter(status="COMPLETED").filter(
        models.Q(completed_course=False)
        | models.Q(completed_at__isnull=True)
        | models.Q(final_score__isnull=True)
    )
    for application in bad_completed.iterator():
        certificate = Certificate.objects.using(database).filter(
            application_id=application.pk,
            status="ACTIVE",
        ).first()
        if certificate:
            application.completed_course = True
            application.completed_at = application.completed_at or certificate.issued_at
            application.final_score = (
                application.final_score
                if application.final_score is not None
                else (application.qualification_score or 0)
            )
            application.save(
                using=database,
                update_fields=["completed_course", "completed_at", "final_score"],
            )
            continue

        target_status = (
            "IN_PROGRESS"
            if application.assigned_cohort_id
            else ("QUALIFIED" if application.qualified else "APPLIED")
        )
        previous_status = application.status
        application.status = target_status
        application.completed_course = False
        application.completed_at = None
        application.final_score = None
        application.save(
            using=database,
            update_fields=["status", "completed_course", "completed_at", "final_score"],
        )
        ApplicationStatusAudit.objects.using(database).create(
            application_id=application.pk,
            from_status=previous_status,
            to_status=target_status,
            reason="Migration repair: legacy COMPLETED row had no completion evidence or certificate.",
            is_repair=True,
        )

    enrolled_statuses = [
        "COHORT_ASSIGNED",
        "IN_PROGRESS",
        "TRAINING",
        "INTERNSHIP_ASSIGNED",
        "COMPLETED",
        "SUSPENDED",
        "TRANSFER_COHORT",
    ]
    missing_cohort = Application.objects.using(database).filter(
        status__in=enrolled_statuses,
        assigned_cohort__isnull=True,
    )
    for application in missing_cohort.iterator():
        previous_status = application.status
        target_status = "QUALIFIED" if application.qualified else "APPLIED"
        application.status = target_status
        application.completed_course = False
        application.completed_at = None
        application.final_score = None
        application.save(
            using=database,
            update_fields=["status", "completed_course", "completed_at", "final_score"],
        )
        Certificate.objects.using(database).filter(
            application_id=application.pk,
            status="ACTIVE",
        ).update(
            status="REVOKED",
            revoked_at=timezone.now(),
            revocation_reason="Migration repair: enrolled lifecycle status had no assigned cohort.",
        )
        ApplicationStatusAudit.objects.using(database).create(
            application_id=application.pk,
            from_status=previous_status,
            to_status=target_status,
            reason="Migration repair: enrolled lifecycle status had no assigned cohort.",
            is_repair=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_alter_application_status'),
        ('certificates', '0002_certificate_recipient_name_and_more'),
        ('cohorts', '0006_cohort_group_chat'),
        ('courses', '0011_alter_course_requires_capstone_and_more'),
        ('students', '0008_alter_studentprofile_profile_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='cohort_status_requires_assigned_cohort',
        ),
        migrations.AlterField(
            model_name='application',
            name='offer_letter_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=common.storage.PrivateMediaStorage(), upload_to=applications.models.offer_letter_path),
        ),
        migrations.RunPython(
            repair_historical_completion_invariants,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['COHORT_ASSIGNED', 'IN_PROGRESS', 'TRAINING', 'INTERNSHIP_ASSIGNED', 'COMPLETED', 'SUSPENDED', 'TRANSFER_COHORT']), _negated=True), ('assigned_cohort__isnull', False), _connector='OR'), name='cohort_status_requires_assigned_cohort'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), _negated=True), models.Q(('completed_course', True), ('completed_at__isnull', False), ('final_score__isnull', False)), _connector='OR'), name='completed_status_requires_completion_evidence'),
        ),
    ]
