# Generated by Django 5.1.4 on 2026-08-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_prescreening_question_bank_prescreening_paper_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescreening',
            name='is_released',
            field=models.BooleanField(db_index=True, default=False, help_text='Admin manually releases this exam. The student Start button is locked until this is True AND the current time is within scheduled_at -> end_time.'),
        ),
    ]
