# Generated by Django 5.1.4 on 2026-08-27 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0024_prescreening_is_released'),
        ('question_bank', '0005_questionbank_lifecycle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescreening',
            name='question_bank',
            field=models.ForeignKey(blank=True, help_text='Approved, open pre-screening question bank assigned to this candidate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_schedules', to='question_bank.questionbank'),
        ),
    ]
