# Generated by Django 5.1.4 on 2026-09-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_alter_prescreening_question_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('EXAM_PENDING', 'Exam Pending'), ('EXAM_COMPLETED', 'Exam Completed'), ('PRESCREENING_PENDING', 'Pre-Screen Interview Pending'), ('PRESCREENING_COMPLETED', 'Pre-Screen Interview Completed'), ('QUALIFIED', 'Qualified'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted'), ('COHORT_ASSIGNED', 'Cohort Assigned'), ('IN_PROGRESS', 'In Progress'), ('TRAINING', 'Training'), ('INTERNSHIP_ASSIGNED', 'Internship Assigned'), ('SOFT_SKILLS', 'Soft Skills'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped'), ('SUSPENDED', 'Suspended'), ('TRANSFER_COHORT', 'Transfer Cohort'), ('CANCELLED', 'Cancelled')], db_index=True, default='APPLIED', max_length=30),
        ),
    ]
