# Generated by Django 5.1.4 on 2026-09-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0026_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescreening',
            name='calendar_event_id',
            field=models.CharField(blank=True, help_text='Google Calendar event ID for this screening meeting.', max_length=255, null=True),
        ),
    ]
