# Generated by Django 5.1.4 on 2026-09-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0027_prescreening_calendar_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescreening',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RESCHEDULED', 'Rescheduled'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=30),
        ),
        migrations.AlterField(
            model_name='prescreeninginterview',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RESCHEDULED', 'Rescheduled'), ('COMPLETED', 'Completed'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=30),
        ),
    ]
