# Generated by Django 5.1.4 on 2026-09-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0028_alter_prescreening_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescreening',
            name='admin_started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when a Platform Admin explicitly opens the pre-screening exam gate for students.', null=True, verbose_name='Admin Started At'),
        ),
    ]
