# Generated by Django 5.1.4 on 2026-09-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0029_prescreening_admin_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_admin_assigned',
            field=models.BooleanField(default=False, help_text='True if this application was directly placed by an Admin without typical pre-screening.'),
        ),
    ]
