# Generated by Django 5.1.4 on 2026-09-09 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0030_application_is_admin_assigned'),
        ('cohorts', '0017_remove_cohort_current_mentor'),
        ('courses', '0013_course_electives_course_is_elective'),
        ('students', '0012_googlestudentidentity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='required_meet_display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='required_meet_display_name_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('assigned_cohort__isnull', False), ('required_meet_display_name_normalized__isnull', False)), fields=('assigned_cohort', 'required_meet_display_name_normalized'), name='unique_meet_name_per_cohort'),
        ),
    ]
