# Generated by Django 5.1.4 on 2026-09-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0031_application_required_meet_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='whatsapp_joined',
            field=models.BooleanField(default=False, help_text='True if the student has explicitly confirmed they joined the WhatsApp group.'),
        ),
    ]
