# Generated by Django 5.1.4 on 2026-08-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_is_linkedin_connected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='github_org_invite_status',
            field=models.CharField(default='NOT_INVITED', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='github_repo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='github_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_github_connected',
            field=models.BooleanField(default=False),
        ),
    ]
