# Generated by Django 5.1.4 on 2026-08-15 06:43

from django.db import migrations, models
from django.utils import timezone


def issue_existing_student_identities(apps, schema_editor):
    StudentProfile = apps.get_model("students", "StudentProfile")
    Application = apps.get_model("applications", "Application")
    issued_profile_ids = Application.objects.filter(
        assigned_cohort__isnull=False,
    ).values_list("student_id", flat=True).distinct()
    StudentProfile.objects.filter(id__in=issued_profile_ids).update(
        student_identity_issued_at=timezone.now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_status_cancelled'),
        ('students', '0003_studentprofile_github_org_invite_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_identity_issued_at',
            field=models.DateTimeField(blank=True, help_text='Issued only after qualification, interview verification, and cohort assignment.', null=True),
        ),
        migrations.RunPython(issue_existing_student_identities, migrations.RunPython.noop),
    ]
