# Generated by Django 5.1.4 on 2026-08-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentprofile_student_identity_issued_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth of the student.', null=True),
        ),
    ]
