# Generated by Django 5.1.4 on 2026-08-17 16:32

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.student_photo_path),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=students.models.student_resume_path),
        ),
    ]
