# Generated by Django 5.1.4 on 2026-08-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_studentprofile_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='verification_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
