# Generated by Django 5.1.4 on 2026-08-18 18:50

import common.validators
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentprofile_verification_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.student_photo_path, validators=[common.validators.validate_profile_photo_file]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=students.models.student_resume_path, validators=[common.validators.validate_resume_file]),
        ),
    ]
