# Generated by Django 5.1.4 on 2026-08-27 09:14

import common.storage
import django.db.models.deletion
import students.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_studentprofile_profile_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPlacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full-Time'), ('CONTRACT', 'Contract'), ('FREELANCE', 'Freelance'), ('INTERNSHIP', 'Internship'), ('OTHER', 'Other')], default='FULL_TIME', max_length=20)),
                ('joining_date', models.DateField()),
                ('offer_letter', models.FileField(blank=True, max_length=500, null=True, storage=common.storage.PrivateMediaStorage(), upload_to=students.models.placement_offer_letter_path)),
                ('official_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING_VERIFICATION', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_remarks', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='students.studentprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_placements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Placement',
                'verbose_name_plural': 'Student Placements',
                'ordering': ['-created_at'],
            },
        ),
    ]
