# Generated by Django 5.1.4 on 2026-09-07 07:17

import common.validators
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_studentplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Student profile banner / cover photo. Maximum 10 MB; JPG, PNG, or WEBP.', null=True, upload_to=students.models.student_banner_path, validators=[common.validators.validate_banner_image_file]),
        ),
    ]
