# Generated by Django 5.1.4 on 2026-09-09 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_studentidentityalias'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleStudentIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_subject_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('google_email', models.EmailField(db_index=True, max_length=254)),
                ('google_profile_name', models.CharField(max_length=255)),
                ('google_profile_name_normalized', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_identity', to='students.studentprofile')),
            ],
            options={
                'verbose_name_plural': 'Google Student Identities',
            },
        ),
    ]
