# Generated by Django 5.1.4 on 2026-09-09 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_googlestudentidentity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlestudentidentity',
            name='google_profile_name_normalized',
        ),
    ]
