# Generated by Django 5.1.4 on 2026-09-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_remove_googlestudentidentity_google_profile_name_normalized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlestudentidentity',
            name='google_subject_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
