# Generated by Django 5.1.4 on 2026-08-13 20:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_cohort_volunteers_alter_cohort_status'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('target_audience', models.CharField(choices=[('ALL', 'All Users'), ('STUDENTS', 'All Students'), ('MENTORS', 'All Mentors'), ('VOLUNTEERS', 'All Volunteers'), ('COHORT', 'Specific Cohort Only')], db_index=True, default='ALL', max_length=20)),
                ('attachment', models.FileField(blank=True, help_text='Optional document, image, or PDF attachment.', null=True, upload_to='announcements/attachments/')),
                ('link_url', models.URLField(blank=True, help_text='Optional external or internal link URL.', max_length=500, null=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned announcements stay at the top of student dashboards.')),
                ('is_active', models.BooleanField(default=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='cohorts.cohort')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success / Achievement'), ('WARNING', 'Warning / Alert'), ('ACTION_REQUIRED', 'Action Required')], default='INFO', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('action_url', models.CharField(blank=True, help_text='Relative URL or dashboard path for action link.', max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('sender_role', models.CharField(blank=True, help_text='Role at submission time: STUDENT, MENTOR, VOLUNTEER', max_length=20)),
                ('category', models.CharField(choices=[('TECHNICAL_ISSUE', 'Technical Issue / Bug'), ('ATTENDANCE', 'Attendance Correction'), ('COURSE_INQUIRY', 'Course / Curriculum Inquiry'), ('OFFER_LETTER', 'Offer Letter'), ('CERTIFICATE', 'Certificate'), ('ASSIGNMENT_EXAM', 'Assignment / Exam Query'), ('VOLUNTEER_JOINING', 'Volunteer Joining Request'), ('MENTOR_SUPPORT', 'Mentor Support / Class Reschedule'), ('VOLUNTEER_SUPPORT', 'Volunteer Support / Session Log'), ('LEAVE_REQUEST', 'Leave Request'), ('OTHER', 'Other General Request')], db_index=True, default='TECHNICAL_ISSUE', max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, help_text='Optional screenshot or document attachment.', null=True, upload_to='requests/attachments/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], db_index=True, default='PENDING', max_length=20)),
                ('admin_remarks', models.TextField(blank=True, help_text='Resolution notes or response from Admin.', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Support Request',
                'verbose_name_plural': 'User Support Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
