# Generated by Django 5.1.4 on 2026-08-13 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_cohort_volunteers_alter_cohort_status'),
        ('common', '0002_announcement_notification_userrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['target_audience', 'is_active'], name='common_anno_target__d95dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['cohort', 'is_active'], name='common_anno_cohort__f770a5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='common_noti_user_id_aae5b0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='common_noti_created_dff411_idx'),
        ),
        migrations.AddIndex(
            model_name='userrequest',
            index=models.Index(fields=['sender', 'status'], name='common_user_sender__cdb7c7_idx'),
        ),
        migrations.AddIndex(
            model_name='userrequest',
            index=models.Index(fields=['category', 'status'], name='common_user_categor_732aab_idx'),
        ),
        migrations.AddIndex(
            model_name='userrequest',
            index=models.Index(fields=['created_at'], name='common_user_created_8ff76f_idx'),
        ),
    ]
