# Generated by Django 5.1.4 on 2026-08-22 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_prescreening_end_time_prescreeninginterview_end_time_and_more'),
        ('common', '0004_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='related_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to='applications.application'),
        ),
        migrations.AddConstraint(
            model_name='userrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('category', 'OFFER_LETTER'), ('status__in', ['PENDING', 'IN_PROGRESS'])), fields=('related_application', 'category'), name='unique_active_offer_letter_request_per_application'),
        ),
    ]
