# Generated by Django 5.1.4 on 2026-08-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_userrequest_related_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='request_number',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
