# Generated by Django 5.1.4 on 2026-08-27 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_achievement_organizationalupdate'),
        ('students', '0008_alter_studentprofile_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='students.studentprofile'),
        ),
    ]
