# Generated by Django 5.1.4 on 2026-08-30 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_achievement_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_code', models.PositiveIntegerField(help_text='Integer version code matching Android BuildConfig.VERSION_CODE (e.g. 2)', unique=True)),
                ('version_name', models.CharField(help_text="Display version string (e.g. '1.1.0')", max_length=50)),
                ('apk_file', models.FileField(blank=True, help_text='Upload the APK file directly to serve from backend media storage', null=True, upload_to='apk/')),
                ('download_url', models.URLField(blank=True, help_text='Optional external/CDN download URL (used if APK file is not uploaded directly)', max_length=500)),
                ('release_notes', models.TextField(help_text='Markdown or bullet points of new features and fixes shown in the in-app update dialog')),
                ('is_mandatory', models.BooleanField(default=False, help_text='If True, prevents dismissal of update dialog and enforces immediate update')),
                ('file_size_bytes', models.BigIntegerField(blank=True, help_text='File size in bytes. Automatically computed if an APK file is uploaded', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active releases are served by the version-check endpoint')),
            ],
            options={
                'verbose_name': 'App Release',
                'verbose_name_plural': 'App Releases',
                'ordering': ['-version_code'],
                'indexes': [models.Index(fields=['is_active', '-version_code'], name='common_appr_is_acti_abae34_idx')],
            },
        ),
    ]
