# Generated by Django 5.1.4 on 2026-09-12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0012_reconcile_notification_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MobilePushDelivery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_session", models.UUIDField()),
                ("event_type", models.CharField(max_length=40)),
                ("class_id", models.CharField(max_length=64)),
                ("scheduled_at", models.DateTimeField()),
                ("server_sent_at", models.DateTimeField()),
                ("device_received_at", models.DateTimeField()),
                ("notification_displayed_at", models.DateTimeField(blank=True, null=True)),
                ("transport_latency_ms", models.PositiveBigIntegerField(default=0)),
                ("schedule_lateness_ms", models.PositiveBigIntegerField(default=0)),
                ("device", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deliveries", to="common.mobilepushdevice")),
                ("notification", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="mobile_deliveries", to="common.notification")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mobile_push_deliveries", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["class_id", "event_type"], name="push_delivery_class_event"),
                    models.Index(fields=["device_received_at"], name="push_delivery_received"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("notification", "device", "event_type"), name="push_delivery_event_unique"),
                ],
            },
        ),
    ]
