# Generated by Django 5.1.4 on 2026-09-20 19:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_mobilepushdelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDeliveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(help_text='Unique key per email transaction (e.g. otp:user_id or application_confirmation:app_id)', max_length=255, unique=True)),
                ('email_category', models.CharField(db_index=True, help_text='Category of the email (e.g. otp, password_reset, application_confirmation)', max_length=100)),
                ('recipient', models.CharField(db_index=True, help_text='Recipient email address (or hashed identifier)', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('provider_attempted', models.CharField(choices=[('ZEPTOMAIL', 'ZeptoMail'), ('GOOGLE_WORKSPACE', 'Google Workspace'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('provider_message_id', models.CharField(blank=True, help_text='Message ID returned by the provider', max_length=255, null=True)),
                ('failure_category', models.CharField(blank=True, help_text='Classification of failure (e.g. timeout, auth_error, invalid_recipient)', max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email Delivery Log',
                'verbose_name_plural': 'Email Delivery Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email_category', 'status'], name='common_emai_email_c_a8575a_idx')],
            },
        ),
    ]
