# Generated by Django 5.1.4 on 2026-08-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_staff_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth.', null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth.', null=True),
        ),
    ]
