# Generated by Django 5.1.4 on 2026-08-22 21:41

import common.validators
import volunteers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_mentorprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Mentor profile photo. Maximum 5 MB; JPG, PNG, or WEBP.', null=True, upload_to=volunteers.models.mentor_photo_path, validators=[common.validators.validate_profile_photo_file]),
        ),
    ]
