# Generated by Django 5.1.4 on 2026-08-22 21:56

import common.validators
import volunteers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_mentorprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Volunteer profile photo. Maximum 5 MB; JPG, PNG, or WEBP.', null=True, upload_to=volunteers.models.volunteer_photo_path, validators=[common.validators.validate_profile_photo_file]),
        ),
    ]
