# Generated by Django 5.1.4 on 2026-08-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0005_volunteerprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='github_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='is_github_connected',
            field=models.BooleanField(default=False),
        ),
    ]
