# Generated by Django 5.1.4 on 2026-09-07 07:17

import common.validators
import volunteers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0006_mentorprofile_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Mentor profile banner / cover photo. Maximum 10 MB; JPG, PNG, or WEBP.', null=True, upload_to=volunteers.models.mentor_banner_path, validators=[common.validators.validate_banner_image_file]),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Volunteer profile banner / cover photo. Maximum 10 MB; JPG, PNG, or WEBP.', null=True, upload_to=volunteers.models.volunteer_banner_path, validators=[common.validators.validate_banner_image_file]),
        ),
    ]
