# Generated by Django 5.1.4 on 2026-09-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_electives_course_is_elective'),
        ('volunteers', '0007_mentorprofile_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Courses this mentor is qualified to teach.', related_name='qualified_mentors', to='courses.course'),
        ),
    ]
