# Generated by Django 5.1.4 on 2026-08-04 07:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_type', models.CharField(choices=[('COURSE', 'Course Feedback'), ('TRAINING', 'Training Feedback'), ('SYSTEM', 'System Feedback'), ('OTHER', 'Other')], default='SYSTEM', max_length=20)),
                ('related_id', models.UUIDField(blank=True, help_text='ID of the course, training, etc.', null=True)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating from 1 to 5')),
                ('comments', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
