# Generated by Django 5.1.4 on 2026-08-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('COURSE', 'Course Feedback'), ('TRAINING', 'Training Feedback'), ('SYSTEM', 'System Feedback'), ('OTHER', 'Other')], db_index=True, default='SYSTEM', max_length=20),
        ),
    ]
