# Generated by Django 5.1.4 on 2026-09-06 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_feedback_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(condition=models.Q(('related_id__isnull', True)), fields=('user', 'feedback_type'), name='unique_feedback_per_user_type_no_entity'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(condition=models.Q(('related_id__isnull', False)), fields=('user', 'feedback_type', 'related_id'), name='unique_feedback_per_user_type_entity'),
        ),
    ]
