# Generated by Django 5.1.4 on 2026-09-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_unique_feedback_per_user_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('COURSE', 'Course Feedback'), ('TRAINING', 'Training Feedback'), ('MENTOR', 'Mentor Feedback'), ('SYSTEM', 'System Feedback'), ('OTHER', 'Other')], db_index=True, default='SYSTEM', max_length=20),
        ),
    ]
