# Generated by Django 5.1.4 on 2026-09-12 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_electives_course_is_elective'),
        ('feedback', '0004_alter_feedback_feedback_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feedback',
            name='unique_feedback_per_user_type_no_entity',
        ),
        migrations.RemoveConstraint(
            model_name='feedback',
            name='unique_feedback_per_user_type_entity',
        ),
        migrations.AddField(
            model_name='feedback',
            name='explanation_rating',
            field=models.CharField(blank=True, choices=[('VERY_CLEAR', 'Very Clear'), ('CLEAR', 'Clear'), ('AVERAGE', 'Average'), ('DIFFICULT_TO_UNDERSTAND', 'Difficult to Understand')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='improvements_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='interaction_rating',
            field=models.CharField(blank=True, choices=[('YES_ALWAYS', 'Yes, Always'), ('SOMETIMES', 'Sometimes'), ('NO', 'No')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Course Module being reviewed.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='courses.coursemodule'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='related_id',
            field=models.UUIDField(blank=True, help_text='ID of the course, training, mentor, etc.', null=True),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(condition=models.Q(('related_id__isnull', True), ('module__isnull', True)), fields=('user', 'feedback_type'), name='unique_feedback_no_entity_no_module'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(condition=models.Q(('related_id__isnull', False), ('module__isnull', True)), fields=('user', 'feedback_type', 'related_id'), name='unique_feedback_entity_no_module'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(condition=models.Q(('related_id__isnull', False), ('module__isnull', False)), fields=('user', 'feedback_type', 'related_id', 'module'), name='unique_feedback_entity_module'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(condition=models.Q(('related_id__isnull', True), ('module__isnull', False)), fields=('user', 'feedback_type', 'module'), name='unique_feedback_no_entity_module'),
        ),
    ]
