# Generated by Django 5.1.4 on 2026-08-13 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_offer_letter_file_and_more'),
        ('certificates', '0001_initial'),
        ('students', '0002_studentprofile_is_linkedin_connected_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='recipient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='applications.application'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('COURSE', 'Course Completion'), ('INTERNSHIP', 'Internship Completion'), ('MERIT', 'Certificate of Merit'), ('VOLUNTEER', 'Volunteer Appreciation'), ('MENTOR', 'Mentor Appreciation'), ('COMPANY', 'Corporate Partner Appreciation'), ('TRUSTEE', 'Trustee Service & Leadership'), ('PARTICIPATION', 'Participation')], db_index=True, default='COURSE', max_length=30),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.studentprofile'),
        ),
    ]
