# Generated by Django 5.1.4 on 2026-08-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Password Reset OTP',
                'verbose_name_plural': 'Password Reset OTPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='has_all_cohorts_access',
            field=models.BooleanField(default=False, help_text='If True, this Volunteer/Mentor is granted access to view and manage all cohorts across the platform.'),
        ),
        migrations.AddField(
            model_name='user',
            name='mapped_email',
            field=models.EmailField(blank=True, db_index=True, help_text='Mapped personal/professional email where notifications & updates are dispatched.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('MENTOR', 'Mentor'), ('VOLUNTEER', 'Volunteer'), ('TRUSTEE', 'Trustee'), ('COMPANY', 'Company'), ('ADMIN', 'Admin')], db_index=True, default='STUDENT', max_length=20),
        ),
    ]
