# Generated by Django 5.1.4 on 2026-08-15 22:48

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearch',
            fields=[
            ],
            options={
                'verbose_name': 'Search User Details (Student/Mentor/Trustee/Volunteer)',
                'verbose_name_plural': 'Search User Details (Student/Mentor/Trustee/Volunteer)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
