# Generated by Django 5.1.4 on 2026-08-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usersearch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersearch',
            options={'verbose_name': 'User Directory Search', 'verbose_name_plural': 'User Directory Search'},
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], help_text='Gender of the user.', max_length=10, null=True),
        ),
    ]
