# Generated by Django 5.1.4 on 2026-08-16 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_usersearch_options_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('ADMINISTRATOR', 'Administrator / Core Team'), ('TRUSTEE', 'Board of Trustees'), ('ADVISORY', 'Advisory Board Member'), ('EXECUTIVE', 'Executive Management')], db_index=True, default='ADMINISTRATOR', help_text='Role category (Administrator, Trustee, Advisory Board, Executive Management)', max_length=30)),
                ('designation', models.CharField(blank=True, help_text='e.g. Founder & Chairman, Board Trustee, Advisory Member, Senior Director, Platform Administrator', max_length=150)),
                ('department', models.CharField(blank=True, help_text='e.g. Board of Trustees, Advisory Council, Academic Operations, Tech & Infrastructure', max_length=150)),
                ('organization_affiliation', models.CharField(blank=True, help_text='External Organization, Institution or Corporate Affiliation', max_length=200)),
                ('expertise', models.TextField(blank=True, help_text='Core Domain, Strategic Guidance, and Advisory Expertise')),
                ('responsibilities', models.TextField(blank=True, help_text='Key administrative responsibilities, governance focus, or advisory areas')),
                ('bio', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('is_public_leadership', models.BooleanField(default=True, help_text='Show this profile on public leadership / advisory board listings')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order in leadership/advisory directory')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role__in': ['ADMIN', 'TRUSTEE', 'VOLUNTEER']}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrative & Leadership Profile',
                'verbose_name_plural': 'Administrative & Leadership Profiles',
                'ordering': ['display_order', 'category', 'designation'],
            },
        ),
    ]
