# Generated by Django 5.1.4 on 2026-08-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_emailverificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationotp',
            name='registration_data',
            field=models.JSONField(blank=True, help_text='Pending registration payload until email OTP is verified.', null=True),
        ),
    ]
