# Generated by Django 5.1.4 on 2026-09-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_administratorprofile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administratorprofile',
            name='category',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator / Core Team'), ('TRUSTEE', 'Board of Trustees'), ('ADVISORY', 'Advisory Board Member'), ('EXECUTIVE', 'Executive Management'), ('VOLUNTEER', 'Volunteer')], db_index=True, default='ADMINISTRATOR', help_text='Role category (Administrator, Trustee, Advisory Board, Executive Management)', max_length=30),
        ),
    ]
