# Generated by Django 5.1.4 on 2026-07-18 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('question', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('TEXT', 'Text'), ('CODING', 'Coding')], default='MCQ', max_length=30)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='EASY', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.JSONField(default=list)),
                ('marks', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('generated_by_ai', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('MIXED', 'Mixed')], default='MIXED', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=45)),
                ('pass_percentage', models.DecimalField(decimal_places=2, default=60, max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('EVALUATED', 'Evaluated')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('qualified', models.BooleanField(blank=True, null=True)),
                ('proctoring_video', models.FileField(blank=True, null=True, upload_to='exams/proctoring/videos/')),
                ('screen_recording', models.FileField(blank=True, null=True, upload_to='exams/proctoring/screens/')),
                ('proctoring_data', models.JSONField(blank=True, default=dict)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='applications.application')),
                ('questions', models.ManyToManyField(blank=True, related_name='exams', to='exams.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
