# Generated by Django 5.1.4 on 2026-08-15 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursemodule'),
        ('exams', '0003_alter_exam_status_alter_question_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduletest',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='courses.coursemodule'),
        ),
    ]
