# Generated by Django 5.1.4 on 2026-08-15 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_moduletest_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalExamAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('launch_nonce', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('IN_PROGRESS', 'In Progress'), ('RESULT_RECEIVED', 'Result Received')], db_index=True, default='CREATED', max_length=20)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('result_received_at', models.DateTimeField(blank=True, null=True)),
                ('result_event_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('result_payload_hash', models.CharField(blank=True, max_length=64)),
                ('integrity_status', models.CharField(blank=True, choices=[('PASSED', 'Passed'), ('FAILED', 'Failed')], max_length=20, null=True)),
                ('proctoring_summary', models.JSONField(blank=True, default=dict)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_attempt', to='exams.exam')),
            ],
            options={
                'verbose_name': 'External Exam Attempt',
                'verbose_name_plural': 'External Exam Attempts',
                'ordering': ('-created_at',),
            },
        ),
    ]
