# Generated by Django 5.1.4 on 2026-08-15 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_externalexamattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduletest',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='questions',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
