# Generated by Django 5.1.4 on 2026-08-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_remove_moduletest_questions_remove_exam_questions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Pre-Screening Exam Result', 'verbose_name_plural': 'Pre-Screening Exam Results'},
        ),
    ]
