# Generated by Django 5.1.4 on 2026-08-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_exam_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='proctoring_data',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='proctoring_video',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='screen_recording',
        ),
        migrations.AddField(
            model_name='exam',
            name='proctor_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Proctor Name'),
        ),
    ]
