# Generated by Django 5.1.4 on 2026-08-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_remove_exam_answers_remove_exam_proctoring_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='total_questions',
            field=models.PositiveIntegerField(default=10, help_text='Number of questions in the exam.'),
        ),
        migrations.AddField(
            model_name='moduletest',
            name='level',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('MIXED', 'Mixed')], default='MIXED', max_length=20),
        ),
        migrations.AddField(
            model_name='moduletest',
            name='total_questions',
            field=models.PositiveIntegerField(default=10, help_text='Number of questions in the module test.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8),
        ),
    ]
