# Generated by Django 5.1.4 on 2026-08-19 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0004_cohort_lst_batch_alter_cohort_status'),
        ('exams', '0009_exam_total_questions_moduletest_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduletest',
            name='cohort',
            field=models.ForeignKey(blank=True, help_text='Optional cohort specific module test.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_tests', to='cohorts.cohort'),
        ),
        migrations.AddField(
            model_name='moduletestsubmission',
            name='cohort',
            field=models.ForeignKey(blank=True, help_text='Associated student cohort.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_test_submissions', to='cohorts.cohort'),
        ),
    ]
