# Generated by Django 5.1.4 on 2026-08-21 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_moduletest_cohort_moduletestsubmission_cohort'),
        ('students', '0008_alter_studentprofile_profile_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalExamAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('EXPIRED', 'Expired')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('question_mapping', models.JSONField(default=list, help_text='List of original question IDs in randomized order.')),
                ('option_mapping', models.JSONField(default=dict, help_text='Dict mapping original question ID to a list of option indices.')),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('submission_time', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_attempts', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_attempts', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Internal Exam Attempt',
                'verbose_name_plural': 'Internal Exam Attempts',
            },
        ),
        migrations.CreateModel(
            name='ExamSecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=50)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to='exams.internalexamattempt')),
            ],
            options={
                'verbose_name': 'Exam Security Event',
                'verbose_name_plural': 'Exam Security Events',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AddConstraint(
            model_name='internalexamattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'IN_PROGRESS')), fields=('student', 'exam'), name='unique_active_internal_attempt'),
        ),
    ]
