# Generated by Django 5.1.4 on 2026-08-22 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0006_cohort_group_chat'),
        ('exams', '0011_internalexamattempt_examsecurityevent_and_more'),
        ('question_bank', '0005_questionbank_lifecycle_status'),
        ('students', '0008_alter_studentprofile_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduletestsubmission',
            options={'ordering': ('-created_at',), 'verbose_name': 'Module Test Submission', 'verbose_name_plural': 'Module Test Submissions'},
        ),
        migrations.AddField(
            model_name='moduletest',
            name='question_bank',
            field=models.ForeignKey(blank=True, help_text='Optional QuestionBank linked for automated evaluation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_module_tests', to='question_bank.questionbank'),
        ),
        migrations.AddConstraint(
            model_name='moduletestsubmission',
            constraint=models.UniqueConstraint(fields=('test', 'student'), name='unique_student_module_test_submission'),
        ),
    ]
