# Generated by Django 5.1.4 on 2026-08-22 22:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def mark_existing_module_test_submissions_submitted(apps, schema_editor):
    ModuleTestSubmission = apps.get_model('exams', 'ModuleTestSubmission')
    ModuleTestSubmission.objects.filter(submitted_at__isnull=False).update(status='SUBMITTED')


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_alter_moduletestsubmission_options_and_more'),
        ('question_bank', '0005_questionbank_lifecycle_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='proctoring_capacity_per_room',
            field=models.PositiveSmallIntegerField(default=50, help_text='Operational planning limit; the video provider does not guarantee this capacity.'),
        ),
        migrations.AddField(
            model_name='exam',
            name='proctoring_enabled',
            field=models.BooleanField(default=True, help_text='Embed a live proctoring room in the internal exam interface.'),
        ),
        migrations.AddField(
            model_name='exam',
            name='proctoring_required',
            field=models.BooleanField(default=True, help_text='Record a security warning whenever the live proctoring room disconnects.'),
        ),
        migrations.AddField(
            model_name='exam',
            name='proctoring_room_count',
            field=models.PositiveSmallIntegerField(default=4, help_text='Number of persisted proctoring rooms used to distribute candidates.'),
        ),
        migrations.AddField(
            model_name='internalexamattempt',
            name='paper_set',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='internalexamattempt',
            name='proctoring_connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internalexamattempt',
            name='proctoring_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='internalexamattempt',
            name='question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internal_exam_attempts', to='question_bank.questionbank'),
        ),
        migrations.AddField(
            model_name='internalexamattempt',
            name='question_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='Immutable server-side copy of the assigned questions and answer key.'),
        ),
        migrations.AddField(
            model_name='moduletestsubmission',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moduletestsubmission',
            name='option_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='moduletestsubmission',
            name='paper_set',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='moduletestsubmission',
            name='question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='module_test_attempts', to='question_bank.questionbank'),
        ),
        migrations.AddField(
            model_name='moduletestsubmission',
            name='question_mapping',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='moduletestsubmission',
            name='question_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='Immutable server-side copy of the assigned module-test paper.'),
        ),
        migrations.AddField(
            model_name='moduletestsubmission',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('EXPIRED', 'Expired')], db_index=True, default='IN_PROGRESS', max_length=20),
        ),
        migrations.RunPython(
            mark_existing_module_test_submissions_submitted,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='ExamProctoringRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_key', models.CharField(db_index=True, max_length=64)),
                ('session_date', models.DateField(db_index=True)),
                ('code', models.CharField(max_length=10)),
                ('room_name', models.CharField(max_length=180, unique=True)),
                ('room_password', models.CharField(max_length=180)),
                ('capacity', models.PositiveSmallIntegerField(default=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_proctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exam_proctoring_rooms', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(blank=True, help_text='Exam used to configure this shared session; candidates may belong to other exams.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proctoring_rooms', to='exams.exam')),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proctoring_rooms', to='question_bank.questionbank')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='internalexamattempt',
            name='proctoring_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='exams.examproctoringroom'),
        ),
        migrations.AddConstraint(
            model_name='examproctoringroom',
            constraint=models.UniqueConstraint(fields=('scope_key', 'code'), name='unique_exam_proctoring_scope_room_code'),
        ),
    ]
