# Generated by Django 5.1.4 on 2026-08-23 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_exam_proctoring_capacity_per_room_and_more'),
        ('students', '0008_alter_studentprofile_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examproctoringroom',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, help_text='Candidates pre-assigned by an administrator. Assessment start honors this room before automatic balancing.', related_name='assigned_proctoring_rooms', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='moduletest',
            name='proctoring_capacity_per_room',
            field=models.PositiveSmallIntegerField(default=50, help_text='Operational planning limit per room.'),
        ),
        migrations.AddField(
            model_name='moduletest',
            name='proctoring_enabled',
            field=models.BooleanField(default=False, help_text='Embed a persisted Jitsi room in this module test.'),
        ),
        migrations.AddField(
            model_name='moduletest',
            name='proctoring_required',
            field=models.BooleanField(default=False, help_text='Require and audit the live proctoring connection for this test.'),
        ),
        migrations.AddField(
            model_name='moduletest',
            name='proctoring_room_count',
            field=models.PositiveSmallIntegerField(default=4, help_text='Number of persisted rooms used to distribute module-test candidates.'),
        ),
        migrations.AddField(
            model_name='moduletestsubmission',
            name='proctoring_connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moduletestsubmission',
            name='proctoring_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_test_submissions', to='exams.examproctoringroom'),
        ),
        migrations.AddField(
            model_name='moduletestsubmission',
            name='proctoring_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('FAILED', 'Failed')], db_index=True, default='NOT_REQUIRED', max_length=20),
        ),
    ]
