# Generated by Django 5.1.4 on 2026-08-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_examproctoringroom_assigned_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduletestsubmission',
            name='integrity_status',
            field=models.CharField(blank=True, choices=[('PASSED', 'Passed'), ('FAILED', 'Failed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='moduletestsubmission',
            name='proctoring_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='moduletestsubmission',
            name='result_event_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='moduletestsubmission',
            name='result_payload_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='moduletestsubmission',
            name='result_source',
            field=models.CharField(choices=[('INTERNAL', 'SURE ProEd examination platform'), ('EXTERNAL', 'External examination platform')], db_index=True, default='INTERNAL', max_length=20),
        ),
    ]
