# Generated by Django 5.1.4 on 2026-08-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_moduletestsubmission_integrity_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartTest',
            fields=[
            ],
            options={
                'verbose_name': 'Start Test',
                'verbose_name_plural': 'Start Test Hub',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('exams.exam',),
        ),
        migrations.AddField(
            model_name='moduletest',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='End time of the module test window.', null=True, verbose_name='Scheduled End Time'),
        ),
        migrations.AddField(
            model_name='moduletest',
            name='is_released',
            field=models.BooleanField(db_index=True, default=False, help_text='Admin releases this module test. Students can start only when released and within window.'),
        ),
        migrations.AddField(
            model_name='moduletest',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Start time of the module test window.', null=True, verbose_name='Scheduled Start Time'),
        ),
    ]
