# Generated by Django 5.1.4 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0016_starttest_moduletest_end_time_moduletest_is_released_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moduletest",
            name="calendar_event_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Google Calendar event ID used to update this meeting without duplicates.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="moduletest",
            name="meeting_link",
            field=models.URLField(
                blank=True,
                help_text="Google Meet URL generated for this course/cohort module-test window.",
                null=True,
            ),
        ),
    ]
