# Generated by Django 5.1.4 on 2026-08-27 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_moduletest_google_meet'),
        ('question_bank', '0005_questionbank_lifecycle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examproctoringroom',
            name='question_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_rooms', to='question_bank.questionbank'),
        ),
    ]
