# Generated by Django 5.1.4 on 2026-09-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0018_alter_examproctoringroom_question_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduletest',
            name='admin_started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when a Platform Admin explicitly opens the test gate for students.', null=True, verbose_name='Admin Started At'),
        ),
    ]
