# Generated by Django 5.1.4 on 2026-09-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_moduletest_admin_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='pass_percentage',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=5),
        ),
    ]
