# Generated by Django 5.1.4 on 2026-09-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0020_alter_exam_pass_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduletestsubmission',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('EXPIRED', 'Expired'), ('MISSED', 'Missed')], db_index=True, default='IN_PROGRESS', max_length=20),
        ),
    ]
