# Generated by Django 5.1.4 on 2026-08-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Non-Medical', 'Non-Medical')], db_index=True, default='Non-Medical', max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='eligibility_criteria',
            field=models.TextField(blank=True, help_text='Custom eligibility criteria configured by Admin. Defaults to prerequisites if not specified.', null=True),
        ),
    ]
