# Generated by Django 5.1.4 on 2026-08-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursemodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='requires_interview',
            field=models.BooleanField(db_index=True, default=True, help_text='If disabled, qualified candidates skip the interview stage and can proceed to professional-profile verification and cohort assignment.'),
        ),
    ]
