# Generated by Django 5.1.4 on 2026-08-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_requires_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='default_screening_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Optional. New applications automatically receive this screening schedule. Leave empty to schedule each application manually later.', null=True, verbose_name='Default pre-screen exam date and time'),
        ),
    ]
