# Generated by Django 5.1.4 on 2026-08-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_repair_coursemodule_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exam_difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('MIXED', 'Mixed')], default='MIXED', help_text='Default difficulty level for pre-screening exams.', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='exam_duration_minutes',
            field=models.PositiveIntegerField(default=45, help_text='Default duration in minutes for pre-screening exams.'),
        ),
        migrations.AddField(
            model_name='course',
            name='exam_pass_percentage',
            field=models.DecimalField(decimal_places=2, default=60, help_text='Default pass percentage required for pre-screening exams.', max_digits=5),
        ),
        migrations.AddField(
            model_name='course',
            name='exam_total_questions',
            field=models.PositiveIntegerField(default=10, help_text='Default number of questions for pre-screening exams.'),
        ),
    ]
