# Generated by Django 5.1.4 on 2026-08-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_exam_difficulty_course_exam_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_prerequisites',
            field=models.JSONField(blank=True, default=list, help_text='Structured list of prerequisite topics for AI question generation. Example: ["C Programming", "Digital Electronics", "Basic Electronics"]'),
        ),
    ]
