# Generated by Django 5.1.4 on 2026-08-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='requires_assignments',
            field=models.BooleanField(default=True, help_text='Whether regular assignments are required for completion.'),
        ),
        migrations.AddField(
            model_name='course',
            name='requires_capstone',
            field=models.BooleanField(default=False, help_text='Whether capstone project is required for completion.'),
        ),
        migrations.AddField(
            model_name='course',
            name='requires_lst_training',
            field=models.BooleanField(default=False, help_text='Whether Life Skills Training (LST) attendance is required for completion.'),
        ),
        migrations.AddField(
            model_name='course',
            name='requires_module_tests',
            field=models.BooleanField(default=False, help_text='Whether module tests are required for completion.'),
        ),
        migrations.AddField(
            model_name='course',
            name='requires_social_activity',
            field=models.BooleanField(default=False, help_text='Whether verified social responsibility activity evidence is required for completion.'),
        ),
        migrations.AddField(
            model_name='course',
            name='requires_soft_skills_training',
            field=models.BooleanField(default=False, help_text='Whether Soft Skills training attendance is required for completion.'),
        ),
        migrations.AddField(
            model_name='course',
            name='requires_tree_plantation',
            field=models.BooleanField(default=False, help_text='Whether verified tree plantation evidence is required for completion.'),
        ),
    ]
