# Generated by Django 5.1.4 on 2026-09-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='electives',
            field=models.ManyToManyField(blank=True, help_text='Select courses that are offered as electives for students enrolled in this course.', related_name='primary_courses', to='courses.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_elective',
            field=models.BooleanField(default=False, help_text='Designates whether this course can be taken as an elective course.'),
        ),
    ]
