# Generated by Django 5.1.4 on 2026-07-18 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohorts', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('assignment_type', models.CharField(choices=[('CODING', 'Coding'), ('PROJECT', 'Project'), ('CAPSTONE', 'Capstone'), ('REPORT', 'Report'), ('OTHER', 'Other')], default='CODING', max_length=20)),
                ('begin_date', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('pass_percentage', models.DecimalField(decimal_places=2, default=60, max_digits=5)),
                ('files', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cohorts.cohort')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_text', models.TextField(blank=True, null=True)),
                ('submission_url', models.URLField(blank=True, null=True)),
                ('files', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField()),
                ('is_late', models.BooleanField(default=False)),
                ('evaluated', models.BooleanField(default=False)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.studentprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('assignment', 'student'), name='unique_assignment_student_submission')],
            },
        ),
    ]
