# Generated by Django 5.1.4 on 2026-08-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapstoneProject',
            fields=[
            ],
            options={
                'verbose_name': 'Capstone Project',
                'verbose_name_plural': 'Capstone Projects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assignments.assignment',),
        ),
        migrations.CreateModel(
            name='CapstoneSubmission',
            fields=[
            ],
            options={
                'verbose_name': 'Capstone Submission',
                'verbose_name_plural': 'Capstone Submissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assignments.submission',),
        ),
    ]
