# Generated by Django 5.1.4 on 2026-08-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_capstoneproject_capstonesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='autograding_enabled',
            field=models.BooleanField(default=False, help_text='Run a server-side, non-executing source review for GitHub submissions.'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='autograding_rubric',
            field=models.TextField(blank=True, help_text='Course-neutral assessment criteria supplied to the automated reviewer.'),
        ),
        migrations.AddField(
            model_name='submission',
            name='auto_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='auto_graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='auto_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='auto_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='submission',
            name='autograding_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Not requested'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='NOT_REQUESTED', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='commit_sha',
            field=models.CharField(blank=True, help_text='Immutable 40-character Git commit used for reproducible review.', max_length=40),
        ),
    ]
