# Generated by Django 5.1.4 on 2026-09-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_assignment_elective'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='resubmission_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this assignment was resubmitted.'),
        ),
    ]
