# Generated by Django 5.1.4 on 2026-09-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_submission_resubmission_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='resubmission_remarks',
            field=models.TextField(blank=True, help_text='Mentor instructions or reasons for requesting a resubmission.', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='resubmission_requested',
            field=models.BooleanField(db_index=True, default=False, help_text='Set by mentor or admin when the student is asked to resubmit.'),
        ),
    ]
