# Generated by Django 5.1.4 on 2026-09-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_submission_resubmission_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allow_late_submissions',
            field=models.BooleanField(default=False),
        ),
    ]
