# Generated by Django 5.1.4 on 2026-08-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_type',
            field=models.CharField(choices=[('LST', 'Life Skills Training'), ('SOFT_SKILLS', 'Soft Skills Training')], db_index=True, default='LST', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingattendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], db_index=True, default='PRESENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='session_date',
            field=models.DateField(db_index=True),
        ),
    ]
