# Generated by Django 5.1.4 on 2026-08-15 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_cohort_volunteers_alter_cohort_status'),
        ('students', '0003_studentprofile_github_org_invite_status_and_more'),
        ('trainings', '0002_alter_training_training_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='cohort',
            field=models.ForeignKey(blank=True, help_text='Leave empty only when the session is shared across every active cohort.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='cohorts.cohort'),
        ),
    ]
