# Generated by Django 5.1.4 on 2026-08-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_trainingsession_cohort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='class_status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20),
        ),
    ]
