# Generated by Django 5.1.4 on 2026-08-15 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_cohort_volunteers_alter_cohort_status'),
        ('trainings', '0004_trainingsession_calendar_event_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingAbsentee',
            fields=[
            ],
            options={
                'verbose_name': 'Training Absentee',
                'verbose_name_plural': 'Training Absentees',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trainings.trainingattendance',),
        ),
        migrations.CreateModel(
            name='TrainingBatchDivision',
            fields=[
            ],
            options={
                'verbose_name': 'Training Batch Division',
                'verbose_name_plural': 'Training Batch Divisions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cohorts.cohort',),
        ),
    ]
