# Generated by Django 5.1.4 on 2026-08-14 21:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_cohort_volunteers_alter_cohort_status'),
        ('companies', '0002_jobposting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('OTHER', 'Other')], default='FULL_TIME', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('apply_url', models.URLField(max_length=500)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_references', to='cohorts.cohort')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_references', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_job_references', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cohort', 'is_active'], name='companies_j_cohort__dac931_idx'), models.Index(fields=['deadline'], name='companies_j_deadlin_64740d_idx')],
            },
        ),
    ]
