# Generated by Django 5.1.4 on 2026-09-04 07:15

import common.storage
import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_jobreference_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=common.storage.OverwriteStorage(), upload_to=companies.models.company_logo_path),
        ),
    ]
