INTERNSHIP_OFFERINGS = [
    # Non Medical
    {
        "code": "ROBOTICS",
        "name": "Robotics Applications",
        "category": "Non-Medical",
        "domain": "Robotics",
        "subject": "Robotics Applications",
        "prerequisites": "B.Tech completed / B.Tech 3rd or 4th year",
    },
    {
        "code": "CYBER-SECURITY",
        "name": "Cybersecurity & Ethical Hacking",
        "category": "Non-Medical",
        "domain": "Cyber Security",
        "subject": "Ethical Hacking",
        "prerequisites": "B.Tech completed / B.Tech 3rd or 4th year",
    },
    {
        "code": "FULL-STACK-WEB",
        "name": "Full Stack Web Development",
        "category": "Non-Medical",
        "domain": "Software Development",
        "subject": "Full Stack Web Development",
        "prerequisites": "B.Tech completed / B.Tech 3rd or 4th year",
    },
    {
        "code": "CORE-JAVA",
        "name": "Java Applications",
        "category": "Non-Medical",
        "domain": "Software Development",
        "subject": "Java Applications",
        "prerequisites": "B.Tech completed / B.Tech 3rd or 4th year",
    },
    {
        "code": "AI-ML",
        "name": "Artificial Intelligence & Machine Learning",
        "category": "Non-Medical",
        "domain": "Artificial Intelligence",
        "subject": "AI & Machine Learning",
        "prerequisites": "B.Tech completed / B.Tech 3rd or 4th year",
    },
    {
        "code": "DIGITAL-MARKETING",
        "name": "Digital Marketing Applications",
        "category": "Non-Medical",
        "domain": "Digital Marketing",
        "subject": "Digital Marketing Applications",
        "prerequisites": "B.Tech completed / B.Tech 3rd or 4th year",
    },
    {
        "code": "EMBEDDED-IOT",
        "name": "Embedded Systems & IOT",
        "category": "Non-Medical",
        "domain": "Embedded Systems",
        "subject": "IoT",
        "prerequisites": "B.Tech completed / B.Tech 3rd or 4th year",
    },
    {
        "code": "FINANCIAL-MODELLING",
        "name": "Integrated Internship in Financial Modelling & Valuation",
        "category": "Non-Medical",
        "domain": "Finance",
        "subject": "Financial Modelling & Valuation",
        "prerequisites": "B.Com, BBA, MBA, CFA and CA aspirants",
    },
    {
        "code": "PCB-DESIGN",
        "name": "PCB Designing",
        "category": "Non-Medical",
        "domain": "Electronics",
        "subject": "PCB Design",
        "prerequisites": "B.Tech, ECE/EEE, 3rd year, 4th year pursuing and B.Tech just completed students can apply",
    },
    {
        "code": "SOFTWARE-TESTING",
        "name": "Software Testing & Tools Applications",
        "category": "Non-Medical",
        "domain": "Quality Assurance",
        "subject": "Software Testing & Tools Applications",
        "prerequisites": "B.Tech completed, B.Tech 3rd or 4th year",
    },
    {
        "code": "UI-UX",
        "name": "UI / UX Designing",
        "category": "Non-Medical",
        "domain": "Design",
        "subject": "UI / UX Designing",
        "prerequisites": "Any Bachelor's degree",
    },
    {
        "code": "VLSI-DESIGN",
        "name": "Integrated VLSI designing - Concept to Silicon",
        "category": "Non-Medical",
        "domain": "VLSI",
        "subject": "VLSI Design",
        "prerequisites": "B.Tech (ECE) completed, or B.Tech (ECE) 3rd or 4th year / MBAs / any other PG",
    },
    {
        "code": "INDUSTRIAL-AUTOMATION",
        "name": "Industrial Automation",
        "category": "Non-Medical",
        "domain": "Automation",
        "subject": "Industrial Automation",
        "prerequisites": "B.Tech completed, B.Tech 3rd or 4th year- ECE, EEE and Instrumentation",
    },
    {
        "code": "CLOUD-DEVOPS",
        "name": "Cloud Computing & DevOps Applications",
        "category": "Non-Medical",
        "domain": "Cloud Computing",
        "subject": "DevOps Applications",
        "prerequisites": "B.Tech completed, B.Tech 3rd or 4th year",
    },
    {
        "code": "CAD-MECHANICAL",
        "name": "AutoCad, Solidworks & CREO",
        "category": "Non-Medical",
        "domain": "Mechanical Design",
        "subject": "CAD / Solidworks / CREO",
        "prerequisites": "B.Tech completed, B.Tech 3rd or 4th year / completed from Mechanical Stream",
    },
    {
        "code": "SALESFORCE",
        "name": "Salesforce Administration & Development",
        "category": "Non-Medical",
        "domain": "CRM",
        "subject": "Salesforce Administration & Development",
        "prerequisites": "Basic knowledge of computer programming",
    },
    {
        "code": "SAP-S4-HANA",
        "name": "SAP S/4 HANA or FICO",
        "category": "Non-Medical",
        "domain": "SAP",
        "subject": "SAP S/4 HANA or FICO",
        "prerequisites": "Basic knowledge of computer programming",
    },
    {
        "code": "SAP-ABAP",
        "name": "SAP ABAP Consultant",
        "category": "Non-Medical",
        "domain": "SAP",
        "subject": "SAP ABAP Consultant",
        "prerequisites": "Basic knowledge of computer programming",
    },
    {
        "code": "GEN-AI",
        "name": "Generative AI - Foundation to Applications",
        "category": "Non-Medical",
        "domain": "Artificial Intelligence",
        "subject": "Generative AI",
        "prerequisites": "Eligibility criteria include 3rd or 4th year B.Tech, MCA, MBA, or other postgraduate students",
    },
    {
        "code": "DSA-JAVA",
        "name": "Data Structures & Algorithms in Java",
        "category": "Non-Medical",
        "domain": "Computer Science",
        "subject": "DSA in Java",
        "prerequisites": "3rd or 4th year B.Tech, MCA, MBA, or other postgraduate students",
    },
    {
        "code": "DATA-ANALYTICS",
        "name": "Data Analytics - Case-based, AI-Augmented, and Mentor-driver",
        "category": "Non-Medical",
        "domain": "Data",
        "subject": "Data Analytics",
        "prerequisites": "3rd or 4th year B.Tech, MCA, MBA, or other postgraduate students",
    },
    {
        "code": "CIVIL-INDUSTRIAL",
        "name": "Industry Focused, AI Augmented, Mentor Led Next Gen Civil Engineering Internship",
        "category": "Non-Medical",
        "domain": "Civil Engineering",
        "subject": "Civil Engineering Internship",
        "prerequisites": "B.Tech completed / B.Tech 3rd or 4th year from Civil Engineering Stream",
    },
    {
        "code": "ACTUARIAL",
        "name": "6-Month Project-based Actuarial Internship",
        "category": "Non-Medical",
        "domain": "Actuarial Science",
        "subject": "Actuarial Internship",
        "prerequisites": "Prerequisites: Pursuing/completed degree in Mathematics, Statistics, Actuarial Science, Economics, Engineering, or related fields, Basic knowledge of statistics, probability, and Excel, Strong analytical skills and willingness to learn with discipline",
    },
    {
        "code": "APP-FULLSTACK-QA",
        "name": "Six-Month Application-Based Full-Stack & QA Automation Internship",
        "category": "Non-Medical",
        "domain": "Software Development",
        "subject": "Full-Stack & QA Automation",
        "prerequisites": "3rd or 4th year B.Tech,/BE, MCA, MBA, or other postgraduate students and B.Tech/BE or PG passout post 2023",
    },
    {
        "code": "SAP-MM",
        "name": "Six-Month AI-Integrated SAP MM Project Internship",
        "category": "Non-Medical",
        "domain": "SAP",
        "subject": "SAP MM",
        "prerequisites": "3rd or 4th year B.Tech,/BE, MCA, MBA, or other postgraduate students and B.Tech/BE or PG passout post 2023",
    },
    {
        "code": "ANDROID-DEV",
        "name": "Six-Month Online Project-Based and AI-Integrated Internship in Android Application Development",
        "category": "Non-Medical",
        "domain": "Mobile Development",
        "subject": "Android Application Development",
        "prerequisites": "3rd or 4th year B.Tech, MCA, MBA, or other postgraduate students",
    },
    # Medical
    {
        "code": "MEDICAL-CODING",
        "name": "Medical Coding",
        "category": "Medical",
        "domain": "Healthcare",
        "subject": "Medical Coding",
        "prerequisites": "BSc, MSc, Pharmacy, MBBS and others with Minimal knowledge in anatomy, physiology and medical terminology",
    },
]


def internship_description():
    return "6-month internship program with 4 months of training followed by 2 months working on real-time projects."


def internship_curriculum():
    return [
        {
            "module": 1,
            "title": "Training Phase",
            "duration_months": 4,
            "topics": ["Foundation", "Hands-on practice", "Assignments"],
        },
        {
            "module": 2,
            "title": "Real-time Project Phase",
            "duration_months": 2,
            "topics": ["Project planning", "Implementation", "Review and presentation"],
        },
    ]
