import io
from io import BytesIO

def generate_attendance_excel_bytes(session):
    import openpyxl
    from openpyxl.styles import Alignment, Font, PatternFill
    from openpyxl.utils import get_column_letter
    
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Detailed Attendance Report"
    
    ws.merge_cells("A1:P1")
    title_cell = ws["A1"]
    title_cell.value = f"Attendance Report: {session.title}"
    title_cell.font = Font(name="Calibri", size=16, bold=True, color="FFFFFF")
    title_cell.fill = PatternFill(start_color="1E3A8A", end_color="1E3A8A", fill_type="solid")
    title_cell.alignment = Alignment(horizontal="center", vertical="center")
    ws.row_dimensions[1].height = 30
    
    # 16-column table (Added Prior Permission + Account Status for discipline verification)
    headers = [
        "Sl.No", "Student ID", "Student Name", "Student Email", "Cohort",
        "Class Date", "Class Start Time", "Class End Time", "Class Duration",
        "Google Meet Join Time", "Google Meet Leave Time",
        "Active Duration", "Attendance %", "Status",
        "Prior Approved", "Account Status"
    ]
    
    header_fill = PatternFill(start_color="3B82F6", end_color="3B82F6", fill_type="solid")
    header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
    
    data = session.google_meet_attendance_data
    class_metrics = data.get("class_metrics", {})
    
    c_start = class_metrics.get("start_time", "")
    c_end = class_metrics.get("end_time", "")
    c_dur_sec = class_metrics.get("duration_seconds", 0)
    c_dur_str = f"{int(c_dur_sec // 60)} min {int(c_dur_sec % 60)} sec" if c_dur_sec else "N/A"
    
    class_date_str = f"{session.class_date:%Y-%m-%d}" if session.class_date else ""
    session_title = session.title or "Regular Class Session"
    
    red_fill = PatternFill(start_color="FECACA", end_color="FECACA", fill_type="solid")
    red_font = Font(name="Calibri", bold=True, color="991B1B")
    green_fill = PatternFill(start_color="D1FAE5", end_color="D1FAE5", fill_type="solid")
    green_font = Font(name="Calibri", bold=True, color="065F46")
    
    # Expected Students — shallow copy so we don't mutate the cached DB object
    sl_no = 1
    expected_students = {k: dict(v) for k, v in (data.get("expected_students") or {}).items()}
    unmatched_participants = list(data.get("unmatched_participants") or [])
    
    # --- IN-MEMORY RE-RECONCILIATION FOR OLD READY RECORDS ---
    # When this record was generated by an older version of the service (before token-overlap
    # matching was added), the same participant may appear BOTH as:
    #   expected_students[sid] = ABSENT / 0 sec
    #   unmatched_participants  = same person / 20 sec
    # Fix this in-memory (no DB write) by re-applying name token-overlap matching between
    # unmatched_participants and expected_students, and merging the data.
    if expected_students and unmatched_participants:
        # Build a lookup: {student_id: (last_name_tokens, email)}
        roster_by_id = {}
        for s_id, s_data in expected_students.items():
            full = (s_data.get("name") or "").strip().lower()
            r_parts = [t for t in full.replace('-', ' ').split() if len(t) > 1]
            email = (s_data.get("email") or "").strip().lower()
            if r_parts or email:
                roster_by_id[s_id] = {"parts": r_parts, "email": email, "last": r_parts[-1] if r_parts else "", "first": r_parts[0] if r_parts else ""}
    
        still_unmatched = []
        for p in unmatched_participants:
            p_email = (p.get("email") or "").strip().lower()
            p_name = (p.get("name") or "").strip().lower()
            p_tokens = {t for t in p_name.replace('-', ' ').split() if len(t) > 1}
    
            matched_sid = None
            # Priority 1: unmatched participant has an email that matches a roster email
            if p_email and p_email not in ("n/a", ""):
                for s_id, r in roster_by_id.items():
                    if r["email"] == p_email:
                        matched_sid = s_id
                        break
            # Priority 2: token-overlap fallback (for participants with no email in stored data)
            if not matched_sid and p_tokens:
                candidate_sid = None
                ambiguous = False
                for s_id, r in roster_by_id.items():
                    last = r["last"]
                    first = r["first"]
                    overlap = set(r["parts"]).intersection(p_tokens)
                    is_match = (
                        (last and last in p_tokens) or
                        (first in p_tokens and len(overlap) >= 2)
                    )
                    if is_match:
                        if candidate_sid is None:
                            candidate_sid = s_id
                        else:
                            ambiguous = True
                            break
                if candidate_sid and not ambiguous:
                    matched_sid = candidate_sid
    
            if matched_sid and matched_sid in expected_students:
                # Merge Google data into the official student row
                s = expected_students[matched_sid]
                dur = p.get("duration_seconds", 0)
                if dur and dur > 0:
                    s["join_time"] = p.get("join_time") or s.get("join_time")
                    s["leave_time"] = p.get("leave_time") or s.get("leave_time")
                    s["duration_seconds"] = dur
                    # Recalculate percentage from conference duration
                    conf_dur = c_dur_sec if c_dur_sec else dur
                    s["attendance_percentage"] = min(100.0, round((dur / conf_dur) * 100, 2)) if conf_dur > 0 else 0
                    s["status"] = "PRESENT"
            else:
                still_unmatched.append(p)
    
        unmatched_participants = still_unmatched
    
        # If any merges happened, persist the corrected data to DB so the admin, 
        # serializer, and subsequent downloads also reflect the correct attendance
        # without requiring another Google API call.
        merged_any = len(still_unmatched) < len(list(data.get("unmatched_participants") or []))
        if merged_any:
            try:
                corrected_data = dict(data)
                corrected_data["expected_students"] = {k: dict(v) for k, v in expected_students.items()}
                corrected_data["unmatched_participants"] = still_unmatched
                session.google_meet_attendance_data = corrected_data
                # Sync the M2M attendees with who is now PRESENT per Google
                present_ids = [
                    s_id for s_id, s_data in expected_students.items()
                    if s_data.get("status") == "PRESENT"
                ]
                if present_ids:
                    session.attendees.set(present_ids)
                else:
                    session.attendees.clear()
                session.save(update_fields=["google_meet_attendance_data"])
                logger.info(
                    f"Persisted reconciled Google attendance for session {session.id} "
                    f"({len(present_ids)} PRESENT student(s))."
                )
                
                # --- AUTO-GENERATE DISCIPLINE AFTER RECONCILIATION ---
                from attendance.services.discipline_service import evaluate_session_discipline
                try:
                    evaluate_session_discipline(session)
                except Exception as e:
                    logger.error(f"Error evaluating discipline for session {session.id} after reconciliation: {e}")
                # -----------------------------------------------------
                
            except Exception as e:
                logger.warning(f"Could not persist reconciled attendance for {session.id}: {e}")
    
    # Pre-compute total_session_seconds from class_metrics for use in both official and guest rows
    total_session_seconds = c_dur_sec if c_dur_sec else 0
    if not total_session_seconds:
        # Fallback: compute from start/end strings
        try:
            from datetime import datetime as _dt
            if c_start and c_end:
                _s = _dt.fromisoformat(str(c_start).replace('Z', '+00:00'))
                _e = _dt.fromisoformat(str(c_end).replace('Z', '+00:00'))
                total_session_seconds = max(0, (_e - _s).total_seconds())
        except Exception:
            total_session_seconds = 0
    
    # --- BACKWARD COMPATIBILITY / OLD SCHEMA FALLBACK ---
    if not expected_students and "participants" in data:
        expected_students = {}
        unmatched_participants = []
        
        # 1. Fetch expected apps
        from applications.models import Application
        if session.class_type == "DOMAIN":
            active_statuses = ["COHORT_ASSIGNED", "IN_PROGRESS", "TRAINING", "INTERNSHIP_ASSIGNED", "TRANSFER_COHORT"]
        elif session.class_type == "SOFTSKILLS":
            active_statuses = ["SOFT_SKILLS"]
        else:
            active_statuses = ["COHORT_ASSIGNED", "IN_PROGRESS", "TRAINING", "INTERNSHIP_ASSIGNED", "SOFT_SKILLS", "TRANSFER_COHORT"]

        expected_apps = Application.objects.select_related('student__user', 'course', 'assigned_cohort').filter(
            status__in=active_statuses,
            student__user__email__isnull=False
        )
        if session.cohort:
            expected_apps = expected_apps.filter(assigned_cohort=session.cohort)
        elif session.lst_batch:
            expected_apps = expected_apps.filter(training_batch=session.lst_batch)
            
        roster_email = {}
        roster_name = {}
        roster_parts = {}
        
        for app in expected_apps:
            u = app.student.user
            email = u.email.strip().lower() if u.email else ""
            name = f"{u.first_name} {u.last_name}".strip().lower()
            
            if email: roster_email[email] = app
            if name: roster_name[name] = app
            
            parts = set(name.replace('-', ' ').split())
            parts = {p for p in parts if len(p) > 1}
            roster_parts[name] = {"app": app, "parts": parts, "name": name}
            
            s_id = str(app.student.id)
            expected_students[s_id] = {
                "student_id": s_id,
                "name": f"{u.first_name} {u.last_name}".strip(),
                "email": email,
                "cohort_name": app.assigned_cohort.name if app.assigned_cohort else "N/A",
                "course_id": app.course.name if app.course else "N/A",
                "cohort_id": app.assigned_cohort.code if app.assigned_cohort else "N/A",
                "status": "ABSENT",
                "join_time": None,
                "leave_time": None,
                "duration_seconds": 0,
                "attendance_percentage": 0,
                "_intervals": []
            }
            
        for p in data.get("participants", []):
            p_email = p.get("email")
            p_email = p_email.strip().lower() if p_email else ""
            p_name = p.get("name")
            p_name = p_name.strip().lower() if p_name else ""
            
            matched_app = None
            
            if p_email and p_email in roster_email:
                matched_app = roster_email[p_email]
            elif p_name and p_name in roster_name:
                matched_app = roster_name[p_name]
            elif p_name:
                p_parts = set(p_name.replace('-', ' ').split())
                p_parts = {pt for pt in p_parts if len(pt) > 1}
                
                candidates = []
                for r_name, r_data in roster_parts.items():
                    intersection = r_data["parts"].intersection(p_parts)
                    if len(intersection) >= 1:
                        candidates.append(r_data["app"])
                        
                if len(candidates) == 1:
                    matched_app = candidates[0]
                    
            if matched_app:
                s_id = str(matched_app.student.id)
                jt_str = p.get("join_time")
                lt_str = p.get("leave_time")
                if jt_str and lt_str:
                    from datetime import datetime
                    try:
                        jt = datetime.fromisoformat(jt_str.replace('Z', '+00:00'))
                        lt = datetime.fromisoformat(lt_str.replace('Z', '+00:00'))
                        expected_students[s_id]["_intervals"].append((jt, lt))
                    except:
                        pass
            else:
                unmatched_participants.append(p)
                
        from django.utils import timezone
        from datetime import datetime
        
        c_start_str = class_metrics.get("start_time")
        c_end_str = class_metrics.get("end_time")
        try:
            if c_start_str:
                d_start = datetime.fromisoformat(c_start_str.replace('Z', '+00:00'))
            else:
                # fallback
                d_start = timezone.make_aware(datetime.combine(session.class_date, session.start_time)) if session.class_date and session.start_time else timezone.now()
                
            if c_end_str:
                d_end = datetime.fromisoformat(c_end_str.replace('Z', '+00:00'))
            else:
                if session.end_time:
                    d_end = timezone.make_aware(datetime.combine(session.class_date, session.end_time))
                else:
                    d_end = timezone.now()
            total_session_seconds = max(0, (d_end - d_start).total_seconds())
            
            # UPDATE string formats for row output
            if not c_start:
                c_start = d_start.isoformat()
            if not c_end:
                c_end = d_end.isoformat()
            if c_dur_sec == 0:
                c_dur_str = f"{int(total_session_seconds // 60)} min {int(total_session_seconds % 60)} sec"
        except:
            total_session_seconds = session.duration.total_seconds() if hasattr(session.duration, 'total_seconds') else 3600
            if c_dur_sec == 0:
                c_dur_str = f"{int(total_session_seconds // 60)} min {int(total_session_seconds % 60)} sec"
            
        for s_id, s_data in expected_students.items():
            intervals = s_data.pop("_intervals", [])
            if intervals:
                intervals.sort(key=lambda x: x[0])
                merged = [intervals[0]]
                for curr in intervals[1:]:
                    last = merged[-1]
                    if curr[0] <= last[1]:
                        merged[-1] = (last[0], max(last[1], curr[1]))
                    else:
                        merged.append(curr)
                        
                join_t = merged[0][0]
                leave_t = max(i[1] for i in merged)
                active_dur = sum((end - start).total_seconds() for start, end in merged)
                
                s_data["join_time"] = join_t.isoformat()
                s_data["leave_time"] = leave_t.isoformat()
                s_data["duration_seconds"] = int(active_dur)
                s_data["attendance_percentage"] = min(100.0, round((active_dur / total_session_seconds) * 100, 2)) if total_session_seconds > 0 else 0
                s_data["status"] = "PRESENT"
                
    # ---- Build counts for CLASS SUMMARY (computed from the now-reconciled data) ----
    total_students = len(expected_students)
    present_count = sum(1 for s in expected_students.values() if s.get("status") == "PRESENT")
    below_threshold_count = sum(
        1 for s in expected_students.values()
        if s.get("attendance_percentage", 0) < 96 and s.get("status") != "ABSENT"
    )
    absent_count = sum(1 for s in expected_students.values() if s.get("status") == "ABSENT")
    whitelisted_count = len([p for p in unmatched_participants
                             if (p.get("email") or "").strip().lower() in
                             {e.strip().lower() for e in (getattr(session, 'guest_emails', None) or []) if e}])
    
    # ---- Resolve summary metadata from real DB fields ----
    course_display = "N/A"
    if session.course and getattr(session.course, 'name', None):
        course_display = session.course.name
    elif session.cohort and getattr(session.cohort, 'course', None) and getattr(session.cohort.course, 'name', None):
        course_display = session.cohort.course.name
    elif session.title:
        course_display = session.title
    
    cohort_display = "N/A"
    if session.cohort:
        cohort_display = getattr(session.cohort, 'code', None) or getattr(session.cohort, 'name', None) or str(session.cohort)
    elif session.lst_batch:
        cohort_display = session.get_lst_batch_display() if hasattr(session, 'get_lst_batch_display') else session.lst_batch
    
    mentor_display = "Not Assigned"
    if getattr(session, 'cohort', None) and getattr(session.cohort, 'mentors', None):
        mentors = session.cohort.mentors.all()
        if mentors.exists():
            m_list = []
            for m in mentors:
                full = m.get_full_name().strip() if hasattr(m, 'get_full_name') else ""
                email = getattr(m, 'email', '')
                m_list.append(f"{full} ({email})".strip() if full else (email or "N/A"))
            mentor_display = ", ".join(m_list)
    
    conducted_by_display = "N/A"
    if session.conducted_by:
        full = session.conducted_by.get_full_name().strip() if hasattr(session.conducted_by, 'get_full_name') else ""
        email = getattr(session.conducted_by, 'email', '')
        role  = getattr(session.conducted_by, 'role', '')
        conducted_by_display = f"{full} ({email})".strip() if full else (email or "N/A")
        if role:
            conducted_by_display += f"  [{role}]"
    
    meet_link_display = session.meeting_link or "N/A"
    
    # Format Google timings for summary (IST-friendly display)
    from datetime import datetime as _dt
    from zoneinfo import ZoneInfo
    _IST = ZoneInfo('Asia/Kolkata')
    def _fmt_dt(iso_str):
        """Format an ISO datetime string to a readable IST time."""
        if not iso_str:
            return "N/A"
        try:
            dt = _dt.fromisoformat(str(iso_str).replace('Z', '+00:00'))
            dt_ist = dt.astimezone(_IST)
            return dt_ist.strftime('%d %b %Y  %I:%M %p IST')
        except Exception:
            return str(iso_str)
    
    summary_start = _fmt_dt(c_start)
    summary_end = _fmt_dt(c_end)
    summary_dur = c_dur_str if c_dur_str and c_dur_str != "N/A" else (
        f"{int(total_session_seconds // 60)} min {int(total_session_seconds % 60)} sec"
        if total_session_seconds else "N/A"
    )
    
    # ---- Emit CLASS SUMMARY block ----
    label_font   = Font(name="Calibri", size=10, bold=True, color="1E3A8A")
    value_font   = Font(name="Calibri", size=10)
    divider_font = Font(name="Calibri", size=9, italic=True, color="6B7280")
    section_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
    section_fill = PatternFill(start_color="1E3A8A", end_color="1E3A8A", fill_type="solid")
    NUM_COLS = len(headers)  # 13
    
    def _summary_row(label, value, bold_value=False):
        """Append a two-cell label/value row spanning the full table width."""
        ws.append([""] * NUM_COLS)
        r = ws.max_row
        ws.cell(row=r, column=1).value = label
        ws.cell(row=r, column=1).font = label_font
        ws.cell(row=r, column=1).alignment = Alignment(horizontal="left", vertical="center", indent=1)
        ws.cell(row=r, column=3).value = value
        fnt = Font(name="Calibri", size=10, bold=bold_value)
        ws.cell(row=r, column=3).font = fnt
        ws.cell(row=r, column=3).alignment = Alignment(horizontal="left", vertical="center")
        ws.merge_cells(start_row=r, start_column=3, end_row=r, end_column=NUM_COLS)
    
    def _section_heading(text):
        ws.append([""] * NUM_COLS)
        r = ws.max_row
        ws.merge_cells(start_row=r, start_column=1, end_row=r, end_column=NUM_COLS)
        ws.cell(row=r, column=1).value = text
        ws.cell(row=r, column=1).font = section_font
        ws.cell(row=r, column=1).fill = section_fill
        ws.cell(row=r, column=1).alignment = Alignment(horizontal="left", vertical="center", indent=1)
        ws.row_dimensions[r].height = 20
    
    def _blank():
        ws.append([""] * NUM_COLS)
    
    # --- Blank row between title and summary ---
    _blank()
    
    _section_heading("CLASS SUMMARY")
    _summary_row("Course / Domain",   course_display)
    _summary_row("Cohort / Group",    cohort_display)
    _summary_row("Mentor / Trainer",  mentor_display)
    _summary_row("Class Date",        class_date_str)
    _summary_row("Google Meet Start",  summary_start)
    _summary_row("Google Meet End",    summary_end)
    _summary_row("Google Meet Duration", summary_dur)
    _blank()
    _summary_row("Total Students",     total_students)
    _summary_row("Present",            present_count)
    _summary_row("Below Threshold (<96%)", below_threshold_count)
    _summary_row("Absent",             absent_count)
    _summary_row("Whitelisted Guests", whitelisted_count)
    _blank()
    _summary_row("Scheduled / Created By", conducted_by_display)
    _summary_row("Google Meet Link",   meet_link_display)
    _blank()
    
    # ---- OFFICIAL STUDENT ATTENDANCE section heading ----
    _section_heading("OFFICIAL STUDENT ATTENDANCE")
    _blank()
    
    # ---- Column headers for student table ----
    ws.append(headers)
    for col_idx, header in enumerate(headers, 1):
        cell = ws.cell(row=ws.max_row, column=col_idx)
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center")
    
    # Pre-fetch real application statuses from DB for all expected students
    from applications.models import Application
    from students.models import StudentProfile
    student_ids = list(expected_students.keys())
    app_status_lookup = {}
    student_code_lookup = {}
    if student_ids:
        app_qs = Application.objects.filter(
            student_id__in=student_ids
        ).values_list('student_id', 'status')
        for sid, app_st in app_qs:
            app_status_lookup[str(sid)] = app_st

        code_qs = StudentProfile.objects.filter(
            id__in=student_ids
        ).values_list('id', 'student_code')
        for sid, scode in code_qs:
            student_code_lookup[str(sid)] = scode or str(sid)

    # Pre-fetch prior permissions for this session (for green highlighting)
    from attendance.models import PriorPermission
    prior_permission_ids = set(
        str(sid) for sid in
        PriorPermission.objects.filter(session=session).values_list('student_id', flat=True)
    )

    for s_id, s_data in expected_students.items():
        duration = s_data.get("duration_seconds", 0)
        minutes = int(duration // 60)
        seconds = int(duration % 60)
        duration_str = f"{minutes} min {seconds} sec" if duration > 0 else "0 sec"
    
        attendance_percentage = s_data.get("attendance_percentage", 0)
        real_app_status = app_status_lookup.get(s_id, "")
        has_prior_permission = s_id in prior_permission_ids

        # Determine status string
        if has_prior_permission:
            status_str = "PRIOR PERMISSION"
        elif real_app_status == "SUSPENDED":
            status_str = "ACCOUNT SUSPENDED"
        elif attendance_percentage < 96 and s_data.get("status") != "ABSENT":
            status_str = "SUSPENSION PENDING"
        else:
            status_str = s_data.get("status", "ABSENT")
    
        # Use human-readable student_code (e.g. STU-22EEE1) instead of UUID
        display_student_id = student_code_lookup.get(s_id, s_id)

        row = [
            sl_no,
            display_student_id,
            s_data.get("name", "N/A"),
            s_data.get("email", "N/A"),
            s_data.get("cohort_name", "N/A"),
            class_date_str,
            c_start,
            c_end,
            c_dur_str,
            s_data.get("join_time") or "",
            s_data.get("leave_time") or "",
            duration_str,
            f"{attendance_percentage}%",
            status_str,
            "Y" if has_prior_permission else "N",
            real_app_status or "N/A"
        ]
        ws.append(row)
    
        # Color coding: Green=Prior Permission, Red=Absent/Suspended/Pending Suspension
        row_len = len(row) + 1
        if has_prior_permission:
            for col_idx in range(1, row_len):
                ws.cell(row=ws.max_row, column=col_idx).fill = green_fill
                ws.cell(row=ws.max_row, column=col_idx).font = green_font
        elif real_app_status == "SUSPENDED" or s_data.get("status") == "ABSENT" or attendance_percentage < 96:
            for col_idx in range(1, row_len):
                ws.cell(row=ws.max_row, column=col_idx).fill = red_fill
                ws.cell(row=ws.max_row, column=col_idx).font = red_font
        sl_no += 1
    
    whitelisted_participants = []
    unauthorized_participants = []
    guest_emails_raw = getattr(session, 'guest_emails', None) or []
    whitelist_emails = {e.strip().lower() for e in guest_emails_raw if e and e.strip()}
    
    # unmatched_participants is already populated from the correct schema source above.
    # Classify each as WHITELISTED GUEST (email in session.guest_emails) or EXTERNAL / UNAUTHORIZED.
    # If Google did not expose the participant email (email = "N/A" / empty), we cannot
    # reliably identify them as whitelisted, so they are treated as EXTERNAL / UNAUTHORIZED.
    for p in unmatched_participants:
        p_email = (p.get("email") or "").strip().lower()
        is_whitelisted = bool(p_email and p_email not in ("n/a", "") and p_email in whitelist_emails)
        if is_whitelisted:
            whitelisted_participants.append(p)
        else:
            unauthorized_participants.append(p)
    
    def render_section(title, p_list, default_status):
        if not p_list:
            return
        for _ in range(5):
            ws.append([])
        ws.append([title])
        ws.merge_cells(start_row=ws.max_row, start_column=1, end_row=ws.max_row, end_column=len(headers))
        ws.cell(row=ws.max_row, column=1).font = Font(bold=True, color="1E3A8A")
        ws.cell(row=ws.max_row, column=1).alignment = Alignment(horizontal="center")
        
        ws.append(headers)
        for col_idx, header in enumerate(headers, 1):
            cell = ws.cell(row=ws.max_row, column=col_idx)
            cell.fill = header_fill
            cell.font = header_font
            cell.alignment = Alignment(horizontal="center", vertical="center")
            
        ext_sl = 1
        for u_data in p_list:
            duration = u_data.get("duration_seconds", 0)
            minutes = int(duration // 60)
            seconds = int(duration % 60)
            duration_str = f"{minutes} min {seconds} sec" if duration > 0 else "0 sec"
            
            u_email = u_data.get("email")
            u_email_str = u_email if u_email else "N/A"
            
            attendance_percentage = u_data.get("attendance_percentage", 0)
            if attendance_percentage == 0 and duration > 0 and total_session_seconds > 0:
                attendance_percentage = min(100.0, round((duration / total_session_seconds) * 100, 2))
                
            ws.append([
                ext_sl,
                "N/A",
                u_data.get("name", "Anonymous"),
                u_email_str,
                class_date_str,
                c_start,
                c_end,
                c_dur_str,
                u_data.get("join_time") or "",
                u_data.get("leave_time") or "",
                duration_str,
                f"{attendance_percentage}%",
                default_status
            ])
            ext_sl += 1
    
    render_section("--- WHITELISTED / ADDITIONAL GOOGLE PARTICIPANTS ---", whitelisted_participants, "WHITELISTED / PRESENT")
    render_section("--- EXTERNAL / UNAUTHORIZED GOOGLE PARTICIPANTS ---", unauthorized_participants, "EXTERNAL / UNAUTHORIZED")
    
    # Auto-adjust column widths based on content
    for col_idx in range(1, len(headers) + 1):
        col_letter = get_column_letter(col_idx)
        max_len = len(str(headers[col_idx-1]))
        for cell in ws[col_letter]:
            if cell.value:
                val_str = str(cell.value)
                # Ignore merged/title headers that span multiple columns
                if not val_str.startswith("---") and not val_str.startswith("Attendance Report:"):
                    max_len = max(max_len, len(val_str))
        ws.column_dimensions[col_letter].width = max(max_len + 3, 12)
    
    from django.http import HttpResponse
    import re
    
    course_name = "Session"
    if session.cohort and session.cohort.course:
        course_name = session.cohort.course.name
    elif session.course:
        course_name = session.course.name
    elif session.title:
        course_name = session.title
        
    safe_course = re.sub(r'[^a-zA-Z0-9_\- ]', '', course_name).strip().replace(' ', '_')
    if len(safe_course) > 100:
        safe_course = safe_course[:100].strip('_')
        
    date_str = session.class_date.strftime('%Y-%m-%d') if session.class_date else "UnknownDate"
    time_str = session.start_time.strftime('%H-%M') if session.start_time else "UnknownTime"
    
    filename = f"{safe_course}_{date_str}_{time_str}.xlsx"
    
    response = HttpResponse(
        content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

    # Save workbook to memory
    output = BytesIO()
    wb.save(output)
    output.seek(0)
    return output.read(), filename
