# Generated by Django 5.1.4 on 2026-08-13 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='volunteered_cohorts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
