# Generated by Django 5.1.4 on 2026-08-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_cohort_volunteers_alter_cohort_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(blank=True, help_text='Optional. Auto-generated from Cohort Code and Course Code if left blank.', max_length=150, null=True),
        ),
    ]
