# Generated by Django 5.1.4 on 2026-08-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0003_alter_cohort_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='lst_batch',
            field=models.CharField(blank=True, choices=[('BATCH_1', 'Batch 1'), ('BATCH_2', 'Batch 2')], help_text='LST Batch assignment for this entire cohort.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open (Enrollment)'), ('ACTIVE', 'Active (Pre-Training)'), ('TRAINING', 'Training'), ('INTERNSHIP', 'Internship'), ('SOFT_SKILLS', 'Soft Skills'), ('COMPLETED', 'Completed (Graduated)'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
