# Generated by Django 5.1.4 on 2026-08-21 16:49

from django.db import migrations, models


def backfill_training_started_at(apps, schema_editor):
    Cohort = apps.get_model("cohorts", "Cohort")
    for cohort in Cohort.objects.filter(status="TRAINING", training_started_at__isnull=True):
        cohort.training_started_at = cohort.updated_at
        cohort.save(update_fields=["training_started_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0004_cohort_lst_batch_alter_cohort_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='github_repositories_last_provisioned_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Most recent completed manual GitHub repository provisioning run.', null=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='training_started_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Recorded automatically the first time the cohort enters Training status.', null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('ACTIVE', 'Active'), ('TRAINING', 'Training'), ('INTERNSHIP', 'Internship'), ('SOFT_SKILLS', 'Soft Skills'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.RunPython(backfill_training_started_at, migrations.RunPython.noop),
    ]
