# Generated by Django 5.1.4 on 2026-08-22 10:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0005_cohort_github_repositories_last_provisioned_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cohort', models.OneToOneField(help_text='Each cohort has at most one active group conversation.', on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='cohorts.cohort')),
            ],
            options={
                'verbose_name': 'Cohort Conversation',
                'verbose_name_plural': 'Cohort Conversations',
            },
        ),
        migrations.CreateModel(
            name='CohortMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft-delete for moderation.')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cohorts.cohortconversation')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cohort Chat Message',
                'verbose_name_plural': 'Cohort Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CohortChatReadState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_chat_read_states', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='cohorts.cohortconversation')),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cohorts.cohortmessage')),
            ],
            options={
                'verbose_name': 'Cohort Chat Read State',
                'verbose_name_plural': 'Cohort Chat Read States',
            },
        ),
        migrations.AddIndex(
            model_name='cohortmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='cohorts_coh_convers_e1888c_idx'),
        ),
        migrations.AddIndex(
            model_name='cohortmessage',
            index=models.Index(fields=['sender', 'created_at'], name='cohorts_coh_sender__fc4593_idx'),
        ),
        migrations.AddIndex(
            model_name='cohortchatreadstate',
            index=models.Index(fields=['user', 'conversation'], name='cohorts_coh_user_id_567d2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cohortchatreadstate',
            unique_together={('conversation', 'user')},
        ),
    ]
