# Generated by Django 5.1.4 on 2026-09-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0009_cohort_code_scoped_to_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortmessage',
            name='is_edited',
            field=models.BooleanField(default=False, help_text='True if the message body was edited after sending.'),
        ),
    ]
