# Generated by Django 5.1.4 on 2026-09-02 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0011_cohort_current_module'),
        ('students', '0009_studentplacement'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubProvisioningQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_username', models.CharField(blank=True, max_length=100, null=True)),
                ('repo_name', models.CharField(max_length=150)),
                ('repo_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED_NO_GITHUB', 'Skipped (No GitHub Username)')], db_index=True, default='PENDING', max_length=25)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_queue_items', to='cohorts.cohort')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_queue_items', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'GitHub Provisioning Queue Item',
                'verbose_name_plural': 'GitHub Provisioning Queue',
                'ordering': ['-created_at'],
            },
        ),
    ]
