# Generated by Django 5.1.4 on 2026-09-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0012_githubprovisioningqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='default_screening_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Optional. When new applications are assigned to this cohort, they automatically receive this screening schedule. Leave empty to schedule applications manually.', null=True, verbose_name='Default pre-screen exam date and time'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='requires_interview',
            field=models.BooleanField(db_index=True, default=True, help_text='If disabled for this cohort, qualified candidates skip the interview stage and proceed directly to student role verification and cohort onboarding.'),
        ),
    ]
