# Generated by Django 5.1.4 on 2026-09-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0013_cohort_default_screening_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='application_end_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Deadline for submitting new applications to this cohort. If null, there is no deadline.', null=True, verbose_name='Application End Date'),
        ),
    ]
