# Generated by Django 5.1.4 on 2026-09-07 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0015_cohort_current_mentor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='current_mentors',
            field=models.ManyToManyField(blank=True, related_name='current_mentored_cohorts_plural', to=settings.AUTH_USER_MODEL),
        ),
    ]
