# Generated by Django 5.1.4 on 2026-09-07 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0016_cohort_current_mentors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='current_mentor',
        ),
    ]
