# Generated by Django 5.1.4 on 2026-09-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0017_remove_cohort_current_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='rules_and_regulations',
            field=models.TextField(blank=True, help_text='Cohort-specific rules and regulations.', null=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='whatsapp_group_link',
            field=models.URLField(blank=True, help_text='WhatsApp Group Link for the cohort.', null=True),
        ),
    ]
