# Generated by Django 5.1.4 on 2026-09-24 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0018_cohort_rules_and_regulations_and_more'),
        ('question_bank', '0005_questionbank_lifecycle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='screening_duration_minutes',
            field=models.PositiveIntegerField(blank=True, default=45, null=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='screening_end_time',
            field=models.DateTimeField(blank=True, help_text='Configured screening window end time.', null=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='screening_pass_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=40.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='screening_question_bank',
            field=models.ForeignKey(blank=True, help_text="Question bank configured for this cohort's pre-screening examination.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort_screenings', to='question_bank.questionbank'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='screening_total_questions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
