# Generated by Django 5.1.4 on 2026-08-13 20:04

from django.db import migrations, models
from attendance.migration_operations import AddFieldIfMissing


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        AddFieldIfMissing(
            model_name='attendance',
            name='class_status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='class_date',
            field=models.DateField(db_index=True),
        ),
    ]
