# Generated by Django 5.1.4 on 2026-08-15 04:37

import django.db.models.deletion
import uuid
from django.db import migrations, models
from attendance.migration_operations import AddFieldIfMissing


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('cohorts', '0002_cohort_volunteers_alter_cohort_status'),
        ('courses', '0002_course_category_course_eligibility_criteria'),
        ('students', '0002_studentprofile_is_linkedin_connected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        AddFieldIfMissing(
            model_name='attendance',
            name='class_status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_type',
            field=models.CharField(choices=[('DOMAIN', 'Domain Class'), ('LST', 'LST Class'), ('CELEBRATION', 'Celebration')], db_index=True, default='DOMAIN', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='courses.course'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='google_meet_attendance_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='guest_emails',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='attendance',
            name='joined_students',
            field=models.ManyToManyField(blank=True, related_name='joined_classes', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lst_batch',
            field=models.CharField(blank=True, choices=[('BATCH_1', 'Batch 1'), ('BATCH_2', 'Batch 2')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='cohorts.cohort'),
        ),
        migrations.CreateModel(
            name='RecurringSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_type', models.CharField(choices=[('DOMAIN', 'Domain Class'), ('LST', 'LST Class'), ('CELEBRATION', 'Celebration')], db_index=True, default='DOMAIN', max_length=20)),
                ('lst_batch', models.CharField(blank=True, choices=[('BATCH_1', 'Batch 1'), ('BATCH_2', 'Batch 2')], max_length=20, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_paused', models.BooleanField(default=False)),
                ('next_run', models.DateTimeField(help_text='The datetime of the next occurrence.')),
                ('frequency_days', models.IntegerField(default=7, help_text='7 for weekly, 14 for alternating Sundays.')),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cohorts.cohort')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbsenceWarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved', models.BooleanField(default=False)),
                ('apology_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APOLOGIZED', 'Apologized'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='attendance.attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_warnings', to='students.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'session')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_session_minutes', models.FloatField(default=0)),
                ('active_minutes', models.FloatField(default=0)),
                ('attendance_percentage', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='attendance.attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='students.studentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['session'], name='attendance__session_14e176_idx'), models.Index(fields=['student'], name='attendance__student_ac63a5_idx'), models.Index(fields=['session', 'student'], name='attendance__session_0d109c_idx')],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
