# Generated by Django 5.1.4 on 2026-08-15 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_calendar_event_id_attendance_class_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionRequestMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_permission_messages', to=settings.AUTH_USER_MODEL)),
                ('warning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='attendance.absencewarning')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
