# Generated by Django 5.1.4 on 2026-08-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_class_status_alter_attendance_class_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ('-class_date', '-start_time'), 'verbose_name': 'Class Timetable', 'verbose_name_plural': 'Class Timetables'},
        ),
    ]
