# Generated by Django 5.1.4 on 2026-08-15 10:48

from django.db import migrations, models
import re


def move_legacy_guest_emails(apps, schema_editor):
    Attendance = apps.get_model("attendance", "Attendance")
    for session in Attendance.objects.exclude(notes__isnull=True).exclude(notes=""):
        guest_emails = list(session.whitelisted_guest_emails or [])
        retained_lines = []
        changed = False
        for line in session.notes.splitlines():
            match = re.match(r"^\s*whitelisted\s+guests?\s*:\s*(.*)$", line, re.IGNORECASE)
            if not match:
                retained_lines.append(line)
                continue
            changed = True
            for value in re.split(r"[,;\s]+", match.group(1).strip()):
                email = value.strip().lower()
                if email and "@" in email and email not in guest_emails:
                    guest_emails.append(email)
        if changed:
            session.whitelisted_guest_emails = guest_emails
            session.notes = "\n".join(retained_lines).strip() or None
            session.save(update_fields=["whitelisted_guest_emails", "notes"])


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='whitelisted_guest_emails',
            field=models.JSONField(blank=True, default=list, help_text='External Google Meet guest emails allowed for this class.'),
        ),
        migrations.RunPython(move_legacy_guest_emails, migrations.RunPython.noop),
    ]
