# Generated by Django 5.1.4 on 2026-08-15 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_permissionrequestmessage'),
        ('attendance', '0004_attendance_whitelisted_guest_emails'),
    ]

    operations = [
    ]
