# Generated by Django 5.1.4 on 2026-08-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_merge_20260816_0253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='class_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='whitelisted_guest_emails',
            field=models.JSONField(blank=True, default=list, help_text='External Google Meet guest emails allowed for this class.', null=True),
        ),
    ]
