# Generated by Django 5.1.4 on 2026-08-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendance_options_alter_attendance_class_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('attendance.attendance',),
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
            ],
            options={
                'verbose_name': 'Class Schedule',
                'verbose_name_plural': 'Class Schedules',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('attendance.attendance',),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='class_type',
            field=models.CharField(choices=[('DOMAIN', 'Regular Domain Class'), ('LST', 'LST Class'), ('SOFTSKILLS', 'Soft Skills Training'), ('CELEBRATION', 'Celebration'), ('TRAINING', 'Training Session')], db_index=True, default='DOMAIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lst_batch',
            field=models.CharField(blank=True, choices=[('BATCH_1', 'Batch 1'), ('BATCH_2', 'Batch 2'), ('BATCH_3', 'Batch 3'), ('BATCH_4', 'Batch 4')], max_length=20, null=True),
        ),
    ]
