# Generated by Django 5.1.4 on 2026-08-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendancerecord_classschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='class_type',
            field=models.CharField(choices=[('DOMAIN', 'Regular Domain Class'), ('LST', 'LST Class'), ('SOFTSKILLS', 'Soft Skills Training'), ('CELEBRATION', 'Celebration'), ('TRAINING', 'Training Session'), ('UNIVERSAL', 'Universal Session')], db_index=True, default='DOMAIN', max_length=20),
        ),
    ]
