# Generated by Django 5.1.4 on 2026-09-02 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_attendance_conducted_by'),
        ('cohorts', '0012_githubprovisioningqueue'),
        ('courses', '0013_course_electives_course_is_elective'),
        ('students', '0009_studentplacement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='class_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['cohort', 'class_date'], name='att_cohort_date_idx'),
        ),
    ]
