# Generated by Django 5.1.4 on 2026-09-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_attendance_historical_attendance_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='portal_join_logs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
