# Generated by Django 5.1.4 on 2026-09-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_alter_attendance_lst_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='lst_batch',
            field=models.CharField(blank=True, choices=[('BATCH_1', 'Batch 1'), ('BATCH_2', 'Batch 2'), ('BATCH_3', 'Batch 3'), ('BATCH_4', 'Batch 4'), ('COMBINED', 'Batch 1 + Batch 2 (Combined)')], max_length=20, null=True),
        ),
    ]
