# Generated by Django 5.1.4 on 2026-09-10 08:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_alter_attendance_lst_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencewarning',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APOLOGIZED', 'Apologized'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='GoogleCalendarAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('calendar_event_id', models.CharField(db_index=True, max_length=255)),
                ('operation_type', models.CharField(max_length=50)),
                ('actor', models.CharField(max_length=100)),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='attendance__created_4bb63c_idx')],
            },
        ),
    ]
